import { CardProps, UserProps } from '../interfaces/typings';

export const cardDetails: CardProps[] = [
	{
		id: 1,
		icon: '/assets/icons/users/users.png',
		title: 'users',
		amount: 2453,
	},
	{
		id: 2,
		icon: '/assets/icons/users/active_users.png',
		title: 'active users',
		amount: 2453,
	},
	{
		id: 3,
		icon: '/assets/icons/users/loan_users.png',
		title: 'users with loans',
		amount: 12453,
	},
	{
		id: 4,
		icon: '/assets/icons/users/savings_users.png',
		title: 'users with savings',
		amount: 102453,
	},
];
export function formatNumber(number: Number | undefined) {
	const numberString = number?.toString();
	return numberString?.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

export const admin = {
	id: 1,
	firstName: 'Ezekiel',
	lastName: 'Udiomuno',
	image: '/assets/images/user-image.jpg',
};

export const userTabs = ['General Details', 'Documents', 'Bank Details', 'Loans', 'Savings', 'App and System'];
export const tableHeaders = ['organization', 'username', 'email', 'phone number', 'date joined', 'status'];

export const usersData: UserProps[] = [
	{
		'id': '654e6ab4a06d6cae28886578',
		'profile_picture': 'https://picsum.photos/200/300?random=780',
		'organization': 'Lendsqr',
		'username': 'Mindy64',
		'fullName': 'Sonya Valdez',
		'email': 'sonyavaldez@zolar.com',
		'date_joined': 'Aug 24, 2022 02:54 PM',
		'status': 'Inactive',
		'phone_number': '+1 (959) 447-2857',
		'acc_tier': 2,
		'acc_balance': 81344997,
		'acc_number': 42850483739,
		'bank_name': 'ORBEAN',
		'bvn': 2222668173,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'sonyavaldez@orbean.com',
		'monthly_income': 3253,
		'loan_repayment': 687.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'May Doyle',
			},
			{
				'platform': 'twitter',
				'handle': '@Marjorie94',
			},
			{
				'platform': 'instagram',
				'handle': '@Brianna58',
			},
		],
		'guarantor': [
			{
				'fullName': 'Deirdre Herman',
				'phone_number': '+1 (902) 495-2529',
				'email': 'deirdreherman@orbean.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Howe Todd',
				'phone_number': '+1 (830) 417-3653',
				'email': 'howetodd@orbean.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Carver Rowland',
				'phone_number': '+1 (897) 546-3116',
				'email': 'carverrowland@orbean.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4f202379eae72e231',
		'profile_picture': 'https://picsum.photos/200/300?random=414',
		'organization': 'Irorun',
		'username': 'Johnston37',
		'fullName': 'Cook Saunders',
		'email': 'cooksaunders@orbean.com',
		'date_joined': 'Dec 20, 2022 08:59 AM',
		'status': 'Active',
		'phone_number': '+1 (953) 572-3321',
		'acc_tier': 1,
		'acc_balance': 61292923,
		'acc_number': 72999260468,
		'bank_name': 'INSURESYS',
		'bvn': 2222682061,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'cooksaunders@insuresys.com',
		'monthly_income': 8015,
		'loan_repayment': 571.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Sullivan Lopez',
			},
			{
				'platform': 'twitter',
				'handle': '@Velazquez66',
			},
			{
				'platform': 'instagram',
				'handle': '@Rosa48',
			},
		],
		'guarantor': [
			{
				'fullName': 'Winters Wiley',
				'phone_number': '+1 (992) 515-3966',
				'email': 'winterswiley@insuresys.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Dollie Mccullough',
				'phone_number': '+1 (961) 591-3669',
				'email': 'dolliemccullough@insuresys.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Charmaine Smith',
				'phone_number': '+1 (897) 405-2925',
				'email': 'charmainesmith@insuresys.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab452e25bb796679c22',
		'profile_picture': 'https://picsum.photos/200/300?random=708',
		'organization': 'Lendstar',
		'username': 'Ward36',
		'fullName': 'Slater Hunter',
		'email': 'slaterhunter@insuresys.com',
		'date_joined': 'Dec 02, 2021 08:00 PM',
		'status': 'Pending',
		'phone_number': '+1 (872) 589-3936',
		'acc_tier': 2,
		'acc_balance': 2203875,
		'acc_number': 81252008994,
		'bank_name': 'TWIGGERY',
		'bvn': 2222660739,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'slaterhunter@twiggery.com',
		'monthly_income': 5400,
		'loan_repayment': 444.40000000000003,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Shelly Huber',
			},
			{
				'platform': 'twitter',
				'handle': '@Macias90',
			},
			{
				'platform': 'instagram',
				'handle': '@Kinney93',
			},
		],
		'guarantor': [
			{
				'fullName': 'Pickett Campbell',
				'phone_number': '+1 (873) 548-2110',
				'email': 'pickettcampbell@twiggery.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Flora Sexton',
				'phone_number': '+1 (896) 439-2436',
				'email': 'florasexton@twiggery.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Mcmillan Powers',
				'phone_number': '+1 (949) 427-3307',
				'email': 'mcmillanpowers@twiggery.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab48e33e2020eef70da',
		'profile_picture': 'https://picsum.photos/200/300?random=834',
		'organization': 'Irorun',
		'username': 'Jeanie35',
		'fullName': 'Stefanie Ward',
		'email': 'stefanieward@twiggery.com',
		'date_joined': 'Sep 15, 2023 10:53 AM',
		'status': 'Inactive',
		'phone_number': '+1 (862) 570-2040',
		'acc_tier': 3,
		'acc_balance': 79338545,
		'acc_number': 11249246069,
		'bank_name': 'COMVENE',
		'bvn': 2222669347,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'stefanieward@comvene.com',
		'monthly_income': 7655,
		'loan_repayment': 710.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Duffy Hines',
			},
			{
				'platform': 'twitter',
				'handle': '@Johnson79',
			},
			{
				'platform': 'instagram',
				'handle': '@Gray58',
			},
		],
		'guarantor': [
			{
				'fullName': 'Jody Fry',
				'phone_number': '+1 (827) 504-3977',
				'email': 'jodyfry@comvene.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Young Leblanc',
				'phone_number': '+1 (929) 423-3384',
				'email': 'youngleblanc@comvene.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Francisca Moss',
				'phone_number': '+1 (910) 493-3452',
				'email': 'franciscamoss@comvene.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab47c52b451be1c5885',
		'profile_picture': 'https://picsum.photos/200/300?random=863',
		'organization': 'Lendsqr',
		'username': 'Irma66',
		'fullName': 'Imogene Hartman',
		'email': 'imogenehartman@comvene.com',
		'date_joined': 'Sep 24, 2020 01:36 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (899) 588-3666',
		'acc_tier': 1,
		'acc_balance': 19986268,
		'acc_number': 51160604649,
		'bank_name': 'ZENOLUX',
		'bvn': 2222683577,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'imogenehartman@zenolux.com',
		'monthly_income': 4454,
		'loan_repayment': 686.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Morgan Nielsen',
			},
			{
				'platform': 'twitter',
				'handle': '@Katy55',
			},
			{
				'platform': 'instagram',
				'handle': '@Zelma79',
			},
		],
		'guarantor': [
			{
				'fullName': 'Yolanda Fischer',
				'phone_number': '+1 (936) 428-2468',
				'email': 'yolandafischer@zenolux.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Sheena Zamora',
				'phone_number': '+1 (885) 555-3620',
				'email': 'sheenazamora@zenolux.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Everett Gibbs',
				'phone_number': '+1 (820) 544-3081',
				'email': 'everettgibbs@zenolux.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4e904d7e7d099be2e',
		'profile_picture': 'https://picsum.photos/200/300?random=145',
		'organization': 'Lendstar',
		'username': 'Jennifer90',
		'fullName': 'Staci Travis',
		'email': 'stacitravis@zenolux.com',
		'date_joined': 'Aug 26, 2021 06:55 AM',
		'status': 'Inactive',
		'phone_number': '+1 (932) 472-2437',
		'acc_tier': 2,
		'acc_balance': 18817550,
		'acc_number': 66987170937,
		'bank_name': 'ZYTRAX',
		'bvn': 2222687118,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'stacitravis@zytrax.com',
		'monthly_income': 9166,
		'loan_repayment': 903.9000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Bird Yates',
			},
			{
				'platform': 'twitter',
				'handle': '@Luisa56',
			},
			{
				'platform': 'instagram',
				'handle': '@Leach47',
			},
		],
		'guarantor': [
			{
				'fullName': 'Estelle Bowers',
				'phone_number': '+1 (893) 420-3980',
				'email': 'estellebowers@zytrax.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Irwin Leach',
				'phone_number': '+1 (863) 479-3681',
				'email': 'irwinleach@zytrax.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Charlotte Mcdowell',
				'phone_number': '+1 (951) 482-3105',
				'email': 'charlottemcdowell@zytrax.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4fe18f36797efd37f',
		'profile_picture': 'https://picsum.photos/200/300?random=585',
		'organization': 'Irorun',
		'username': 'Reilly78',
		'fullName': 'Anna Cotton',
		'email': 'annacotton@zytrax.com',
		'date_joined': 'Nov 23, 2022 09:54 PM',
		'status': 'Pending',
		'phone_number': '+1 (945) 542-3952',
		'acc_tier': 2,
		'acc_balance': 22277657,
		'acc_number': 16949986112,
		'bank_name': 'ISONUS',
		'bvn': 2222685761,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'annacotton@isonus.com',
		'monthly_income': 5324,
		'loan_repayment': 872.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Eaton Hickman',
			},
			{
				'platform': 'twitter',
				'handle': '@Minerva32',
			},
			{
				'platform': 'instagram',
				'handle': '@Clarice59',
			},
		],
		'guarantor': [
			{
				'fullName': 'Alexandria Key',
				'phone_number': '+1 (852) 451-2068',
				'email': 'alexandriakey@isonus.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Mitzi Clarke',
				'phone_number': '+1 (999) 449-2802',
				'email': 'mitziclarke@isonus.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Bowers Riggs',
				'phone_number': '+1 (922) 522-3075',
				'email': 'bowersriggs@isonus.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab422ec527d04cc41a1',
		'profile_picture': 'https://picsum.photos/200/300?random=653',
		'organization': 'Irorun',
		'username': 'Kathie85',
		'fullName': 'Deloris Moreno',
		'email': 'delorismoreno@isonus.com',
		'date_joined': 'Sep 11, 2021 10:03 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (922) 424-2761',
		'acc_tier': 3,
		'acc_balance': 52502896,
		'acc_number': 66053779812,
		'bank_name': 'VURBO',
		'bvn': 2222683017,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'delorismoreno@vurbo.com',
		'monthly_income': 9794,
		'loan_repayment': 848.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Alexander Jones',
			},
			{
				'platform': 'twitter',
				'handle': '@Lidia72',
			},
			{
				'platform': 'instagram',
				'handle': '@Margery30',
			},
		],
		'guarantor': [
			{
				'fullName': 'Lacy Barker',
				'phone_number': '+1 (834) 491-3170',
				'email': 'lacybarker@vurbo.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Flossie Aguilar',
				'phone_number': '+1 (962) 580-2315',
				'email': 'flossieaguilar@vurbo.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Sondra Fernandez',
				'phone_number': '+1 (913) 409-3239',
				'email': 'sondrafernandez@vurbo.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4ea483d8932688599',
		'profile_picture': 'https://picsum.photos/200/300?random=460',
		'organization': 'Irorun',
		'username': 'Ball87',
		'fullName': 'Helga Mcneil',
		'email': 'helgamcneil@vurbo.com',
		'date_joined': 'Mar 21, 2020 09:40 AM',
		'status': 'Pending',
		'phone_number': '+1 (989) 517-2910',
		'acc_tier': 1,
		'acc_balance': 85449966,
		'acc_number': 81566083351,
		'bank_name': 'DAISU',
		'bvn': 2222680650,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'helgamcneil@daisu.com',
		'monthly_income': 6597,
		'loan_repayment': 754.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Terra Pena',
			},
			{
				'platform': 'twitter',
				'handle': '@Wanda93',
			},
			{
				'platform': 'instagram',
				'handle': '@Todd60',
			},
		],
		'guarantor': [
			{
				'fullName': 'Pearlie Taylor',
				'phone_number': '+1 (931) 402-3101',
				'email': 'pearlietaylor@daisu.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Noel Estes',
				'phone_number': '+1 (982) 556-2763',
				'email': 'noelestes@daisu.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'White Chapman',
				'phone_number': '+1 (974) 425-2471',
				'email': 'whitechapman@daisu.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab499e2ac4183228922',
		'profile_picture': 'https://picsum.photos/200/300?random=235',
		'organization': 'Lendstar',
		'username': 'Brock69',
		'fullName': 'Freda Dawson',
		'email': 'fredadawson@daisu.com',
		'date_joined': 'May 29, 2020 02:36 PM',
		'status': 'Inactive',
		'phone_number': '+1 (999) 507-2066',
		'acc_tier': 3,
		'acc_balance': 57572688,
		'acc_number': 30650335033,
		'bank_name': 'PROFLEX',
		'bvn': 2222688757,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'fredadawson@proflex.com',
		'monthly_income': 7211,
		'loan_repayment': 704.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Conley Mcgee',
			},
			{
				'platform': 'twitter',
				'handle': '@Rena83',
			},
			{
				'platform': 'instagram',
				'handle': '@Jewel79',
			},
		],
		'guarantor': [
			{
				'fullName': 'Villarreal Ray',
				'phone_number': '+1 (988) 598-3388',
				'email': 'villarrealray@proflex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Eloise Graham',
				'phone_number': '+1 (806) 411-3680',
				'email': 'eloisegraham@proflex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Christi Mcdaniel',
				'phone_number': '+1 (916) 533-3853',
				'email': 'christimcdaniel@proflex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4e9028feabe15eeb7',
		'profile_picture': 'https://picsum.photos/200/300?random=733',
		'organization': 'Lendsqr',
		'username': 'Stokes98',
		'fullName': 'Miranda Cleveland',
		'email': 'mirandacleveland@proflex.com',
		'date_joined': 'Mar 07, 2021 06:37 AM',
		'status': 'Pending',
		'phone_number': '+1 (917) 481-3826',
		'acc_tier': 1,
		'acc_balance': 85815086,
		'acc_number': 58364076181,
		'bank_name': 'VICON',
		'bvn': 2222666536,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'mirandacleveland@vicon.com',
		'monthly_income': 7552,
		'loan_repayment': 903.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Erica Shaw',
			},
			{
				'platform': 'twitter',
				'handle': '@Blanchard81',
			},
			{
				'platform': 'instagram',
				'handle': '@Caitlin53',
			},
		],
		'guarantor': [
			{
				'fullName': 'Byrd Murphy',
				'phone_number': '+1 (924) 447-3405',
				'email': 'byrdmurphy@vicon.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Morris Petersen',
				'phone_number': '+1 (841) 437-3743',
				'email': 'morrispetersen@vicon.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Strong Bruce',
				'phone_number': '+1 (964) 531-2191',
				'email': 'strongbruce@vicon.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4d75aab860ac61fe5',
		'profile_picture': 'https://picsum.photos/200/300?random=381',
		'organization': 'Irorun',
		'username': 'Lynda97',
		'fullName': 'Mayo Mcguire',
		'email': 'mayomcguire@vicon.com',
		'date_joined': 'Nov 09, 2023 12:56 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (959) 423-2594',
		'acc_tier': 3,
		'acc_balance': 28537129,
		'acc_number': 39273566201,
		'bank_name': 'BITENDREX',
		'bvn': 2222691295,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'mayomcguire@bitendrex.com',
		'monthly_income': 7248,
		'loan_repayment': 485.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Oliver Cooke',
			},
			{
				'platform': 'twitter',
				'handle': '@Humphrey77',
			},
			{
				'platform': 'instagram',
				'handle': '@Hoffman97',
			},
		],
		'guarantor': [
			{
				'fullName': 'Aileen Hardin',
				'phone_number': '+1 (803) 465-3935',
				'email': 'aileenhardin@bitendrex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Raymond Parker',
				'phone_number': '+1 (998) 548-2227',
				'email': 'raymondparker@bitendrex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Kate Reese',
				'phone_number': '+1 (889) 457-2389',
				'email': 'katereese@bitendrex.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4c06341acb2a622c8',
		'profile_picture': 'https://picsum.photos/200/300?random=272',
		'organization': 'Lendsqr',
		'username': 'Melody92',
		'fullName': 'Amy Delacruz',
		'email': 'amydelacruz@bitendrex.com',
		'date_joined': 'Jun 22, 2023 08:06 AM',
		'status': 'Active',
		'phone_number': '+1 (888) 519-2909',
		'acc_tier': 1,
		'acc_balance': 1239695,
		'acc_number': 59489709910,
		'bank_name': 'COMBOT',
		'bvn': 2222681380,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'amydelacruz@combot.com',
		'monthly_income': 4863,
		'loan_repayment': 592.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Mable Velasquez',
			},
			{
				'platform': 'twitter',
				'handle': '@Mabel99',
			},
			{
				'platform': 'instagram',
				'handle': '@Catalina48',
			},
		],
		'guarantor': [
			{
				'fullName': 'Alma Maldonado',
				'phone_number': '+1 (959) 570-3657',
				'email': 'almamaldonado@combot.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Shepard David',
				'phone_number': '+1 (993) 428-2059',
				'email': 'sheparddavid@combot.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Dillard Moran',
				'phone_number': '+1 (931) 545-2125',
				'email': 'dillardmoran@combot.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4096c95cb65ae9769',
		'profile_picture': 'https://picsum.photos/200/300?random=11',
		'organization': 'Lendstar',
		'username': 'Hernandez69',
		'fullName': 'Ann Maddox',
		'email': 'annmaddox@combot.com',
		'date_joined': 'Dec 28, 2022 11:16 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (933) 559-3311',
		'acc_tier': 2,
		'acc_balance': 55398127,
		'acc_number': 86586876313,
		'bank_name': 'MYOPIUM',
		'bvn': 2222659445,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'annmaddox@myopium.com',
		'monthly_income': 9703,
		'loan_repayment': 582,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Darcy Gould',
			},
			{
				'platform': 'twitter',
				'handle': '@Poole64',
			},
			{
				'platform': 'instagram',
				'handle': '@Briana92',
			},
		],
		'guarantor': [
			{
				'fullName': 'Valarie Gibson',
				'phone_number': '+1 (985) 485-2712',
				'email': 'valariegibson@myopium.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Ware Chase',
				'phone_number': '+1 (938) 546-2280',
				'email': 'warechase@myopium.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Austin Ayala',
				'phone_number': '+1 (880) 563-2002',
				'email': 'austinayala@myopium.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab44843f4fefd2c287a',
		'profile_picture': 'https://picsum.photos/200/300?random=926',
		'organization': 'Irorun',
		'username': 'Alyce93',
		'fullName': 'Yvonne May',
		'email': 'yvonnemay@myopium.com',
		'date_joined': 'Jan 25, 2020 06:16 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (982) 532-3275',
		'acc_tier': 3,
		'acc_balance': 97376796,
		'acc_number': 46425426448,
		'bank_name': 'RUGSTARS',
		'bvn': 2222666503,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'yvonnemay@rugstars.com',
		'monthly_income': 3840,
		'loan_repayment': 671.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Olga Lindsey',
			},
			{
				'platform': 'twitter',
				'handle': '@Jannie81',
			},
			{
				'platform': 'instagram',
				'handle': '@Karyn45',
			},
		],
		'guarantor': [
			{
				'fullName': 'Stein Schwartz',
				'phone_number': '+1 (881) 459-3217',
				'email': 'steinschwartz@rugstars.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Naomi Horton',
				'phone_number': '+1 (943) 439-2973',
				'email': 'naomihorton@rugstars.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Cummings Conrad',
				'phone_number': '+1 (873) 496-3434',
				'email': 'cummingsconrad@rugstars.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4aef72f4d2cdf67de',
		'profile_picture': 'https://picsum.photos/200/300?random=984',
		'organization': 'Irorun',
		'username': 'Wagner91',
		'fullName': 'Lorena Ballard',
		'email': 'lorenaballard@rugstars.com',
		'date_joined': 'Jan 19, 2021 09:22 AM',
		'status': 'Pending',
		'phone_number': '+1 (829) 511-2145',
		'acc_tier': 2,
		'acc_balance': 11998836,
		'acc_number': 39805228482,
		'bank_name': 'FANGOLD',
		'bvn': 2222683035,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'lorenaballard@fangold.com',
		'monthly_income': 7660,
		'loan_repayment': 415.20000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Banks Aguirre',
			},
			{
				'platform': 'twitter',
				'handle': '@Avery94',
			},
			{
				'platform': 'instagram',
				'handle': '@Cleveland48',
			},
		],
		'guarantor': [
			{
				'fullName': 'Andrea Baird',
				'phone_number': '+1 (995) 595-2240',
				'email': 'andreabaird@fangold.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Fuentes Ryan',
				'phone_number': '+1 (878) 557-3494',
				'email': 'fuentesryan@fangold.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Vicky Davis',
				'phone_number': '+1 (855) 572-3264',
				'email': 'vickydavis@fangold.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4af671fe5ab6f85b5',
		'profile_picture': 'https://picsum.photos/200/300?random=337',
		'organization': 'Lendsqr',
		'username': 'Melinda92',
		'fullName': 'Guerra York',
		'email': 'guerrayork@fangold.com',
		'date_joined': 'Nov 24, 2022 08:52 AM',
		'status': 'Active',
		'phone_number': '+1 (930) 516-2200',
		'acc_tier': 3,
		'acc_balance': 61796538,
		'acc_number': 9697699261,
		'bank_name': 'MAROPTIC',
		'bvn': 2222657984,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'guerrayork@maroptic.com',
		'monthly_income': 7347,
		'loan_repayment': 421.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Madeleine Melendez',
			},
			{
				'platform': 'twitter',
				'handle': '@Acevedo81',
			},
			{
				'platform': 'instagram',
				'handle': '@Sue37',
			},
		],
		'guarantor': [
			{
				'fullName': 'Gena Matthews',
				'phone_number': '+1 (927) 415-3967',
				'email': 'genamatthews@maroptic.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Ortiz Bender',
				'phone_number': '+1 (820) 451-2999',
				'email': 'ortizbender@maroptic.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Moran Hamilton',
				'phone_number': '+1 (942) 507-3207',
				'email': 'moranhamilton@maroptic.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4c54743a0cddb12ac',
		'profile_picture': 'https://picsum.photos/200/300?random=377',
		'organization': 'Irorun',
		'username': 'Becky57',
		'fullName': 'Odonnell Clay',
		'email': 'odonnellclay@maroptic.com',
		'date_joined': 'Mar 22, 2022 09:30 AM',
		'status': 'Active',
		'phone_number': '+1 (840) 407-3721',
		'acc_tier': 2,
		'acc_balance': 14501112,
		'acc_number': 10474833978,
		'bank_name': 'ACCUFARM',
		'bvn': 2222681113,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'odonnellclay@accufarm.com',
		'monthly_income': 4508,
		'loan_repayment': 734.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Randi Dunn',
			},
			{
				'platform': 'twitter',
				'handle': '@Concepcion69',
			},
			{
				'platform': 'instagram',
				'handle': '@Marla33',
			},
		],
		'guarantor': [
			{
				'fullName': 'Shanna Brady',
				'phone_number': '+1 (989) 436-2190',
				'email': 'shannabrady@accufarm.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Cox Hess',
				'phone_number': '+1 (934) 549-3439',
				'email': 'coxhess@accufarm.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Gwendolyn Kane',
				'phone_number': '+1 (987) 505-3081',
				'email': 'gwendolynkane@accufarm.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4b2d714441dfc8117',
		'profile_picture': 'https://picsum.photos/200/300?random=445',
		'organization': 'Irorun',
		'username': 'Jimenez84',
		'fullName': 'Elaine Curry',
		'email': 'elainecurry@accufarm.com',
		'date_joined': 'Aug 25, 2021 03:21 PM',
		'status': 'Active',
		'phone_number': '+1 (850) 434-3805',
		'acc_tier': 2,
		'acc_balance': 73512139,
		'acc_number': 51145909041,
		'bank_name': 'REMOTION',
		'bvn': 2222657999,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'elainecurry@remotion.com',
		'monthly_income': 7231,
		'loan_repayment': 409.90000000000003,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Ivy Santiago',
			},
			{
				'platform': 'twitter',
				'handle': '@Dana85',
			},
			{
				'platform': 'instagram',
				'handle': '@Michael41',
			},
		],
		'guarantor': [
			{
				'fullName': 'Paulette Mills',
				'phone_number': '+1 (957) 528-3259',
				'email': 'paulettemills@remotion.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Swanson Berry',
				'phone_number': '+1 (915) 543-2266',
				'email': 'swansonberry@remotion.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Hendrix Case',
				'phone_number': '+1 (882) 449-3477',
				'email': 'hendrixcase@remotion.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab409e71f40d1aa4b08',
		'profile_picture': 'https://picsum.photos/200/300?random=789',
		'organization': 'Irorun',
		'username': 'Simone48',
		'fullName': 'Nieves Mooney',
		'email': 'nievesmooney@remotion.com',
		'date_joined': 'Dec 05, 2021 05:57 AM',
		'status': 'Pending',
		'phone_number': '+1 (978) 560-2369',
		'acc_tier': 1,
		'acc_balance': 7734716,
		'acc_number': 91427009879,
		'bank_name': 'PROTODYNE',
		'bvn': 2222678122,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'nievesmooney@protodyne.com',
		'monthly_income': 9176,
		'loan_repayment': 474.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Mamie Thomas',
			},
			{
				'platform': 'twitter',
				'handle': '@Latasha86',
			},
			{
				'platform': 'instagram',
				'handle': '@Gillespie30',
			},
		],
		'guarantor': [
			{
				'fullName': 'Myra Wood',
				'phone_number': '+1 (988) 489-2318',
				'email': 'myrawood@protodyne.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Alvarado Santos',
				'phone_number': '+1 (852) 587-3820',
				'email': 'alvaradosantos@protodyne.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Cooley Riddle',
				'phone_number': '+1 (923) 430-3964',
				'email': 'cooleyriddle@protodyne.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4efaceb3387523a30',
		'profile_picture': 'https://picsum.photos/200/300?random=646',
		'organization': 'Lendstar',
		'username': 'Maureen30',
		'fullName': 'Morton Mcleod',
		'email': 'mortonmcleod@protodyne.com',
		'date_joined': 'May 21, 2022 04:10 PM',
		'status': 'Active',
		'phone_number': '+1 (983) 584-2898',
		'acc_tier': 2,
		'acc_balance': 30598203,
		'acc_number': 83868823130,
		'bank_name': 'ZILLACTIC',
		'bvn': 2222699341,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'mortonmcleod@zillactic.com',
		'monthly_income': 9748,
		'loan_repayment': 970.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Fannie Glover',
			},
			{
				'platform': 'twitter',
				'handle': '@Smith33',
			},
			{
				'platform': 'instagram',
				'handle': '@Palmer85',
			},
		],
		'guarantor': [
			{
				'fullName': 'Eula Bray',
				'phone_number': '+1 (809) 461-3971',
				'email': 'eulabray@zillactic.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Ingram Love',
				'phone_number': '+1 (858) 429-2555',
				'email': 'ingramlove@zillactic.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Allison Obrien',
				'phone_number': '+1 (851) 448-3842',
				'email': 'allisonobrien@zillactic.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4bbfd8e11d359910d',
		'profile_picture': 'https://picsum.photos/200/300?random=782',
		'organization': 'Lendstar',
		'username': 'Martin98',
		'fullName': 'Lee Workman',
		'email': 'leeworkman@zillactic.com',
		'date_joined': 'Jun 17, 2021 09:09 AM',
		'status': 'Active',
		'phone_number': '+1 (829) 499-3282',
		'acc_tier': 1,
		'acc_balance': 98823454,
		'acc_number': 44881037640,
		'bank_name': 'ANIVET',
		'bvn': 2222691437,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'leeworkman@anivet.com',
		'monthly_income': 6373,
		'loan_repayment': 664.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Patel Holt',
			},
			{
				'platform': 'twitter',
				'handle': '@Baird54',
			},
			{
				'platform': 'instagram',
				'handle': '@Cornelia62',
			},
		],
		'guarantor': [
			{
				'fullName': 'Bates Martinez',
				'phone_number': '+1 (996) 524-3262',
				'email': 'batesmartinez@anivet.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Delia Mullen',
				'phone_number': '+1 (845) 518-3047',
				'email': 'deliamullen@anivet.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Moreno Lamb',
				'phone_number': '+1 (906) 596-3536',
				'email': 'morenolamb@anivet.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4701a1a5f133474b7',
		'profile_picture': 'https://picsum.photos/200/300?random=262',
		'organization': 'Lendsqr',
		'username': 'Adriana74',
		'fullName': 'Boyd Avery',
		'email': 'boydavery@anivet.com',
		'date_joined': 'Nov 24, 2022 07:29 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (897) 470-2352',
		'acc_tier': 2,
		'acc_balance': 18718107,
		'acc_number': 36087679728,
		'bank_name': 'MEMORA',
		'bvn': 2222686592,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'boydavery@memora.com',
		'monthly_income': 5018,
		'loan_repayment': 438.70000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Cindy Mccoy',
			},
			{
				'platform': 'twitter',
				'handle': '@Adkins58',
			},
			{
				'platform': 'instagram',
				'handle': '@Mayer64',
			},
		],
		'guarantor': [
			{
				'fullName': 'Campbell Fletcher',
				'phone_number': '+1 (828) 567-2062',
				'email': 'campbellfletcher@memora.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Ryan Holmes',
				'phone_number': '+1 (917) 517-2217',
				'email': 'ryanholmes@memora.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Ebony Vincent',
				'phone_number': '+1 (869) 595-3605',
				'email': 'ebonyvincent@memora.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab47ad55dfa376476df',
		'profile_picture': 'https://picsum.photos/200/300?random=889',
		'organization': 'Lendsqr',
		'username': 'Chandra39',
		'fullName': 'Magdalena Medina',
		'email': 'magdalenamedina@memora.com',
		'date_joined': 'Jun 19, 2022 07:35 AM',
		'status': 'Active',
		'phone_number': '+1 (842) 401-3195',
		'acc_tier': 1,
		'acc_balance': 61232653,
		'acc_number': 34154775988,
		'bank_name': 'KNEEDLES',
		'bvn': 2222688980,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'magdalenamedina@kneedles.com',
		'monthly_income': 8666,
		'loan_repayment': 405.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Navarro Beasley',
			},
			{
				'platform': 'twitter',
				'handle': '@Kristie86',
			},
			{
				'platform': 'instagram',
				'handle': '@Sweeney62',
			},
		],
		'guarantor': [
			{
				'fullName': 'Adams Cox',
				'phone_number': '+1 (995) 577-2496',
				'email': 'adamscox@kneedles.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Candice Levy',
				'phone_number': '+1 (833) 516-3297',
				'email': 'candicelevy@kneedles.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Fletcher Nunez',
				'phone_number': '+1 (967) 444-3448',
				'email': 'fletchernunez@kneedles.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab47e9c7a68a037741b',
		'profile_picture': 'https://picsum.photos/200/300?random=393',
		'organization': 'Lendsqr',
		'username': 'Soto75',
		'fullName': 'Crawford Durham',
		'email': 'crawforddurham@kneedles.com',
		'date_joined': 'Sep 25, 2020 10:11 AM',
		'status': 'Active',
		'phone_number': '+1 (823) 553-2484',
		'acc_tier': 3,
		'acc_balance': 59509887,
		'acc_number': 10337233483,
		'bank_name': 'PHARMEX',
		'bvn': 2222686894,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'crawforddurham@pharmex.com',
		'monthly_income': 3154,
		'loan_repayment': 976.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Lee Ruiz',
			},
			{
				'platform': 'twitter',
				'handle': '@Coffey40',
			},
			{
				'platform': 'instagram',
				'handle': '@Ramirez89',
			},
		],
		'guarantor': [
			{
				'fullName': 'Dorothea Decker',
				'phone_number': '+1 (947) 501-3864',
				'email': 'dorotheadecker@pharmex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Maddox Knox',
				'phone_number': '+1 (835) 548-2678',
				'email': 'maddoxknox@pharmex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Elba Adkins',
				'phone_number': '+1 (976) 499-2106',
				'email': 'elbaadkins@pharmex.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab443cf928a8ca49056',
		'profile_picture': 'https://picsum.photos/200/300?random=781',
		'organization': 'Lendsqr',
		'username': 'Juarez66',
		'fullName': 'Angelina Small',
		'email': 'angelinasmall@pharmex.com',
		'date_joined': 'Dec 12, 2021 01:48 PM',
		'status': 'Inactive',
		'phone_number': '+1 (809) 586-3983',
		'acc_tier': 1,
		'acc_balance': 34711157,
		'acc_number': 62761195212,
		'bank_name': 'VIOCULAR',
		'bvn': 2222664581,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'angelinasmall@viocular.com',
		'monthly_income': 6563,
		'loan_repayment': 488.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Tamara Parks',
			},
			{
				'platform': 'twitter',
				'handle': '@Tyler52',
			},
			{
				'platform': 'instagram',
				'handle': '@Keith77',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ruthie Mayer',
				'phone_number': '+1 (879) 439-2587',
				'email': 'ruthiemayer@viocular.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Faulkner Duncan',
				'phone_number': '+1 (837) 599-2128',
				'email': 'faulknerduncan@viocular.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Elisabeth Paul',
				'phone_number': '+1 (849) 479-3427',
				'email': 'elisabethpaul@viocular.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4eff96befa2b3b98a',
		'profile_picture': 'https://picsum.photos/200/300?random=432',
		'organization': 'Irorun',
		'username': 'Serrano31',
		'fullName': 'Gallegos Cooper',
		'email': 'gallegoscooper@viocular.com',
		'date_joined': 'Feb 08, 2020 12:41 AM',
		'status': 'Active',
		'phone_number': '+1 (811) 516-3198',
		'acc_tier': 2,
		'acc_balance': 83785704,
		'acc_number': 53601475288,
		'bank_name': 'CAPSCREEN',
		'bvn': 2222674955,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'gallegoscooper@capscreen.com',
		'monthly_income': 9017,
		'loan_repayment': 504,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Frost Norris',
			},
			{
				'platform': 'twitter',
				'handle': '@Luz40',
			},
			{
				'platform': 'instagram',
				'handle': '@Hewitt90',
			},
		],
		'guarantor': [
			{
				'fullName': 'Mayra Pate',
				'phone_number': '+1 (974) 415-2103',
				'email': 'mayrapate@capscreen.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Alston Williams',
				'phone_number': '+1 (961) 463-2433',
				'email': 'alstonwilliams@capscreen.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Luann Collins',
				'phone_number': '+1 (827) 563-2948',
				'email': 'luanncollins@capscreen.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4d15eed961d4b7e4d',
		'profile_picture': 'https://picsum.photos/200/300?random=777',
		'organization': 'Lendstar',
		'username': 'Queen44',
		'fullName': 'Cochran Contreras',
		'email': 'cochrancontreras@capscreen.com',
		'date_joined': 'Aug 07, 2020 11:36 AM',
		'status': 'Pending',
		'phone_number': '+1 (867) 544-3981',
		'acc_tier': 1,
		'acc_balance': 80256594,
		'acc_number': 83247579583,
		'bank_name': 'COMVEY',
		'bvn': 2222665772,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'cochrancontreras@comvey.com',
		'monthly_income': 4937,
		'loan_repayment': 778.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Miriam Brennan',
			},
			{
				'platform': 'twitter',
				'handle': '@Griffith41',
			},
			{
				'platform': 'instagram',
				'handle': '@Flynn39',
			},
		],
		'guarantor': [
			{
				'fullName': 'Mathis Stevens',
				'phone_number': '+1 (986) 528-2191',
				'email': 'mathisstevens@comvey.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Holmes Boyer',
				'phone_number': '+1 (975) 575-3087',
				'email': 'holmesboyer@comvey.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Montgomery Miranda',
				'phone_number': '+1 (988) 422-2404',
				'email': 'montgomerymiranda@comvey.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab41bdf3fa36f1744f9',
		'profile_picture': 'https://picsum.photos/200/300?random=420',
		'organization': 'Lendsqr',
		'username': 'Hicks89',
		'fullName': 'Kristin Zimmerman',
		'email': 'kristinzimmerman@comvey.com',
		'date_joined': 'Mar 27, 2023 10:11 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (980) 557-2308',
		'acc_tier': 3,
		'acc_balance': 83801093,
		'acc_number': 31948754715,
		'bank_name': 'XUMONK',
		'bvn': 2222692974,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'kristinzimmerman@xumonk.com',
		'monthly_income': 5073,
		'loan_repayment': 618,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Workman Roy',
			},
			{
				'platform': 'twitter',
				'handle': '@Carroll95',
			},
			{
				'platform': 'instagram',
				'handle': '@Hendricks80',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ada Lynch',
				'phone_number': '+1 (852) 424-3305',
				'email': 'adalynch@xumonk.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Gardner Meadows',
				'phone_number': '+1 (948) 462-2024',
				'email': 'gardnermeadows@xumonk.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Cervantes Leon',
				'phone_number': '+1 (920) 541-2815',
				'email': 'cervantesleon@xumonk.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4d6a72215aa9e8eaa',
		'profile_picture': 'https://picsum.photos/200/300?random=182',
		'organization': 'Irorun',
		'username': 'Saunders99',
		'fullName': 'Marisa Bradford',
		'email': 'marisabradford@xumonk.com',
		'date_joined': 'Aug 13, 2023 04:00 AM',
		'status': 'Inactive',
		'phone_number': '+1 (925) 449-3301',
		'acc_tier': 1,
		'acc_balance': 18930097,
		'acc_number': 71130612195,
		'bank_name': 'LIMOZEN',
		'bvn': 2222672175,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'marisabradford@limozen.com',
		'monthly_income': 3157,
		'loan_repayment': 573.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Norris Hunt',
			},
			{
				'platform': 'twitter',
				'handle': '@Vera73',
			},
			{
				'platform': 'instagram',
				'handle': '@Penny89',
			},
		],
		'guarantor': [
			{
				'fullName': 'Salas Estrada',
				'phone_number': '+1 (883) 518-2897',
				'email': 'salasestrada@limozen.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Brown Carr',
				'phone_number': '+1 (871) 562-3173',
				'email': 'browncarr@limozen.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Ruth Boone',
				'phone_number': '+1 (817) 496-3270',
				'email': 'ruthboone@limozen.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4cd02430ac32d7fc2',
		'profile_picture': 'https://picsum.photos/200/300?random=838',
		'organization': 'Lendstar',
		'username': 'Joyce74',
		'fullName': 'Elena Wiggins',
		'email': 'elenawiggins@limozen.com',
		'date_joined': 'Jan 25, 2021 05:01 AM',
		'status': 'Pending',
		'phone_number': '+1 (925) 531-3298',
		'acc_tier': 1,
		'acc_balance': 4815990,
		'acc_number': 86712784349,
		'bank_name': 'TERSANKI',
		'bvn': 2222693840,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'elenawiggins@tersanki.com',
		'monthly_income': 6940,
		'loan_repayment': 977,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Hunt Spears',
			},
			{
				'platform': 'twitter',
				'handle': '@Helena60',
			},
			{
				'platform': 'instagram',
				'handle': '@Norman43',
			},
		],
		'guarantor': [
			{
				'fullName': 'Annette Wilkins',
				'phone_number': '+1 (862) 576-2898',
				'email': 'annettewilkins@tersanki.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Kathy Cortez',
				'phone_number': '+1 (947) 565-3390',
				'email': 'kathycortez@tersanki.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Hillary Dyer',
				'phone_number': '+1 (935) 582-3808',
				'email': 'hillarydyer@tersanki.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4879d4f43a237d875',
		'profile_picture': 'https://picsum.photos/200/300?random=606',
		'organization': 'Irorun',
		'username': 'Doyle57',
		'fullName': 'Dona Christensen',
		'email': 'donachristensen@tersanki.com',
		'date_joined': 'Jul 10, 2023 08:12 PM',
		'status': 'Pending',
		'phone_number': '+1 (968) 442-3718',
		'acc_tier': 2,
		'acc_balance': 84386820,
		'acc_number': 36521466333,
		'bank_name': 'TERRASYS',
		'bvn': 2222679862,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'donachristensen@terrasys.com',
		'monthly_income': 9547,
		'loan_repayment': 675.9000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Malinda Hudson',
			},
			{
				'platform': 'twitter',
				'handle': '@Kemp57',
			},
			{
				'platform': 'instagram',
				'handle': '@Meadows78',
			},
		],
		'guarantor': [
			{
				'fullName': 'Cassie Hart',
				'phone_number': '+1 (944) 464-3285',
				'email': 'cassiehart@terrasys.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Gay Chang',
				'phone_number': '+1 (949) 451-3016',
				'email': 'gaychang@terrasys.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Young Irwin',
				'phone_number': '+1 (847) 504-3137',
				'email': 'youngirwin@terrasys.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab458987c4033e4b602',
		'profile_picture': 'https://picsum.photos/200/300?random=170',
		'organization': 'Lendstar',
		'username': 'Browning69',
		'fullName': 'Marilyn Castaneda',
		'email': 'marilyncastaneda@terrasys.com',
		'date_joined': 'Aug 09, 2020 04:03 AM',
		'status': 'Active',
		'phone_number': '+1 (952) 581-2809',
		'acc_tier': 1,
		'acc_balance': 58196520,
		'acc_number': 80378521156,
		'bank_name': 'ANOCHA',
		'bvn': 2222675457,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'marilyncastaneda@anocha.com',
		'monthly_income': 8586,
		'loan_repayment': 311.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Aurelia Middleton',
			},
			{
				'platform': 'twitter',
				'handle': '@Alissa59',
			},
			{
				'platform': 'instagram',
				'handle': '@Martha73',
			},
		],
		'guarantor': [
			{
				'fullName': 'Orr Greene',
				'phone_number': '+1 (943) 516-3096',
				'email': 'orrgreene@anocha.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Snow Mathis',
				'phone_number': '+1 (909) 416-3618',
				'email': 'snowmathis@anocha.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Matthews Mcdonald',
				'phone_number': '+1 (936) 436-3136',
				'email': 'matthewsmcdonald@anocha.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab46a5a40bdcc517238',
		'profile_picture': 'https://picsum.photos/200/300?random=651',
		'organization': 'Lendsqr',
		'username': 'Alicia76',
		'fullName': 'Delacruz Hoover',
		'email': 'delacruzhoover@anocha.com',
		'date_joined': 'Nov 11, 2020 03:39 AM',
		'status': 'Pending',
		'phone_number': '+1 (947) 581-3397',
		'acc_tier': 1,
		'acc_balance': 63178409,
		'acc_number': 47806106023,
		'bank_name': 'ORBIXTAR',
		'bvn': 2222669109,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'delacruzhoover@orbixtar.com',
		'monthly_income': 8158,
		'loan_repayment': 620.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Karla Duffy',
			},
			{
				'platform': 'twitter',
				'handle': '@Katherine75',
			},
			{
				'platform': 'instagram',
				'handle': '@Allison55',
			},
		],
		'guarantor': [
			{
				'fullName': 'Franco Adams',
				'phone_number': '+1 (910) 505-3666',
				'email': 'francoadams@orbixtar.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Etta Johnson',
				'phone_number': '+1 (834) 557-2800',
				'email': 'ettajohnson@orbixtar.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Janet Blackwell',
				'phone_number': '+1 (973) 553-2085',
				'email': 'janetblackwell@orbixtar.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4053b91bda0124d82',
		'profile_picture': 'https://picsum.photos/200/300?random=242',
		'organization': 'Lendsqr',
		'username': 'Calderon62',
		'fullName': 'Lucile Sutton',
		'email': 'lucilesutton@orbixtar.com',
		'date_joined': 'Dec 03, 2020 07:04 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (987) 484-2216',
		'acc_tier': 1,
		'acc_balance': 64491446,
		'acc_number': 71973527346,
		'bank_name': 'ZIALACTIC',
		'bvn': 2222670505,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'lucilesutton@zialactic.com',
		'monthly_income': 4139,
		'loan_repayment': 849.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Daisy Tucker',
			},
			{
				'platform': 'twitter',
				'handle': '@Lilia91',
			},
			{
				'platform': 'instagram',
				'handle': '@Carrillo69',
			},
		],
		'guarantor': [
			{
				'fullName': 'Roberts Mckee',
				'phone_number': '+1 (820) 463-3111',
				'email': 'robertsmckee@zialactic.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Cash Gomez',
				'phone_number': '+1 (869) 596-3736',
				'email': 'cashgomez@zialactic.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Luna Mack',
				'phone_number': '+1 (839) 545-3042',
				'email': 'lunamack@zialactic.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab46e2013cc3a324b36',
		'profile_picture': 'https://picsum.photos/200/300?random=197',
		'organization': 'Irorun',
		'username': 'Rush93',
		'fullName': 'Fitzpatrick Kline',
		'email': 'fitzpatrickkline@zialactic.com',
		'date_joined': 'Aug 22, 2020 02:50 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (823) 418-2551',
		'acc_tier': 3,
		'acc_balance': 79738393,
		'acc_number': 59904567736,
		'bank_name': 'MEDALERT',
		'bvn': 2222698386,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'fitzpatrickkline@medalert.com',
		'monthly_income': 5535,
		'loan_repayment': 894.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Aida Stephens',
			},
			{
				'platform': 'twitter',
				'handle': '@Pearson43',
			},
			{
				'platform': 'instagram',
				'handle': '@Mccoy31',
			},
		],
		'guarantor': [
			{
				'fullName': 'Contreras Jackson',
				'phone_number': '+1 (821) 468-3028',
				'email': 'contrerasjackson@medalert.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Randolph Cunningham',
				'phone_number': '+1 (858) 402-2657',
				'email': 'randolphcunningham@medalert.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Lucinda Phillips',
				'phone_number': '+1 (924) 433-3614',
				'email': 'lucindaphillips@medalert.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab45235b7d3e61d7fe1',
		'profile_picture': 'https://picsum.photos/200/300?random=255',
		'organization': 'Lendstar',
		'username': 'Dixon91',
		'fullName': 'Doris Bauer',
		'email': 'dorisbauer@medalert.com',
		'date_joined': 'Aug 25, 2021 07:40 AM',
		'status': 'Active',
		'phone_number': '+1 (967) 423-2511',
		'acc_tier': 3,
		'acc_balance': 89883750,
		'acc_number': 39554068508,
		'bank_name': 'BIFLEX',
		'bvn': 2222675009,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'dorisbauer@biflex.com',
		'monthly_income': 3530,
		'loan_repayment': 695.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Dee Mathews',
			},
			{
				'platform': 'twitter',
				'handle': '@Blankenship81',
			},
			{
				'platform': 'instagram',
				'handle': '@Tonya40',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ellison Poole',
				'phone_number': '+1 (841) 534-2031',
				'email': 'ellisonpoole@biflex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Barrera Roberts',
				'phone_number': '+1 (818) 581-3399',
				'email': 'barreraroberts@biflex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Angela Macdonald',
				'phone_number': '+1 (953) 475-2350',
				'email': 'angelamacdonald@biflex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab42e588f3fd1c3c0fa',
		'profile_picture': 'https://picsum.photos/200/300?random=645',
		'organization': 'Lendstar',
		'username': 'William45',
		'fullName': 'Blanca Everett',
		'email': 'blancaeverett@biflex.com',
		'date_joined': 'Mar 24, 2021 08:26 PM',
		'status': 'Pending',
		'phone_number': '+1 (899) 400-2339',
		'acc_tier': 1,
		'acc_balance': 77332183,
		'acc_number': 14362227763,
		'bank_name': 'GREEKER',
		'bvn': 2222665952,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'blancaeverett@greeker.com',
		'monthly_income': 5734,
		'loan_repayment': 905.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Hardin Sargent',
			},
			{
				'platform': 'twitter',
				'handle': '@Loretta38',
			},
			{
				'platform': 'instagram',
				'handle': '@Daniels42',
			},
		],
		'guarantor': [
			{
				'fullName': 'Bettye Joyce',
				'phone_number': '+1 (987) 487-2147',
				'email': 'bettyejoyce@greeker.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Jocelyn Mercado',
				'phone_number': '+1 (808) 456-3386',
				'email': 'jocelynmercado@greeker.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Frances Andrews',
				'phone_number': '+1 (843) 483-3938',
				'email': 'francesandrews@greeker.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4d19f6399830d5342',
		'profile_picture': 'https://picsum.photos/200/300?random=76',
		'organization': 'Lendsqr',
		'username': 'Christa85',
		'fullName': 'Abbott Munoz',
		'email': 'abbottmunoz@greeker.com',
		'date_joined': 'Nov 30, 2020 06:38 AM',
		'status': 'Active',
		'phone_number': '+1 (898) 496-2884',
		'acc_tier': 1,
		'acc_balance': 60947406,
		'acc_number': 29416666881,
		'bank_name': 'APEXIA',
		'bvn': 2222691577,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'abbottmunoz@apexia.com',
		'monthly_income': 5240,
		'loan_repayment': 463.8,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Ethel Fuentes',
			},
			{
				'platform': 'twitter',
				'handle': '@Annie82',
			},
			{
				'platform': 'instagram',
				'handle': '@Tina55',
			},
		],
		'guarantor': [
			{
				'fullName': 'Aguilar Fisher',
				'phone_number': '+1 (825) 566-3985',
				'email': 'aguilarfisher@apexia.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Gould Browning',
				'phone_number': '+1 (948) 475-2175',
				'email': 'gouldbrowning@apexia.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Nikki Vinson',
				'phone_number': '+1 (990) 521-3096',
				'email': 'nikkivinson@apexia.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab43214eae57c1652cb',
		'profile_picture': 'https://picsum.photos/200/300?random=954',
		'organization': 'Lendsqr',
		'username': 'Sosa73',
		'fullName': 'Mack Johnston',
		'email': 'mackjohnston@apexia.com',
		'date_joined': 'Jul 16, 2022 05:46 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (912) 554-3190',
		'acc_tier': 3,
		'acc_balance': 47641863,
		'acc_number': 36925019087,
		'bank_name': 'QUONK',
		'bvn': 2222673914,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'mackjohnston@quonk.com',
		'monthly_income': 9964,
		'loan_repayment': 867.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Robert Raymond',
			},
			{
				'platform': 'twitter',
				'handle': '@Jennings53',
			},
			{
				'platform': 'instagram',
				'handle': '@Liz97',
			},
		],
		'guarantor': [
			{
				'fullName': 'Eugenia Hatfield',
				'phone_number': '+1 (900) 488-3234',
				'email': 'eugeniahatfield@quonk.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Marylou Crosby',
				'phone_number': '+1 (942) 433-2563',
				'email': 'maryloucrosby@quonk.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Velasquez Terrell',
				'phone_number': '+1 (859) 427-2765',
				'email': 'velasquezterrell@quonk.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4f49a792de62536a6',
		'profile_picture': 'https://picsum.photos/200/300?random=114',
		'organization': 'Lendstar',
		'username': 'Kent42',
		'fullName': 'Lindsay Montgomery',
		'email': 'lindsaymontgomery@quonk.com',
		'date_joined': 'Jun 24, 2021 09:20 PM',
		'status': 'Active',
		'phone_number': '+1 (873) 595-2080',
		'acc_tier': 2,
		'acc_balance': 21871264,
		'acc_number': 77227195785,
		'bank_name': 'QUILK',
		'bvn': 2222697157,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'lindsaymontgomery@quilk.com',
		'monthly_income': 4649,
		'loan_repayment': 634.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Evans Downs',
			},
			{
				'platform': 'twitter',
				'handle': '@Leah68',
			},
			{
				'platform': 'instagram',
				'handle': '@Francis64',
			},
		],
		'guarantor': [
			{
				'fullName': 'Summers Stein',
				'phone_number': '+1 (820) 550-2995',
				'email': 'summersstein@quilk.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Barron Rodriguez',
				'phone_number': '+1 (878) 482-2516',
				'email': 'barronrodriguez@quilk.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Stephenson Cooley',
				'phone_number': '+1 (856) 433-3368',
				'email': 'stephensoncooley@quilk.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab497ee53cebdcb993b',
		'profile_picture': 'https://picsum.photos/200/300?random=220',
		'organization': 'Lendsqr',
		'username': 'Felecia73',
		'fullName': 'Shelley Berger',
		'email': 'shelleyberger@quilk.com',
		'date_joined': 'Oct 23, 2023 01:42 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (914) 545-2958',
		'acc_tier': 3,
		'acc_balance': 51069153,
		'acc_number': 81551134251,
		'bank_name': 'PORTALINE',
		'bvn': 2222672291,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'shelleyberger@portaline.com',
		'monthly_income': 4172,
		'loan_repayment': 902.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Marva Banks',
			},
			{
				'platform': 'twitter',
				'handle': '@Earline78',
			},
			{
				'platform': 'instagram',
				'handle': '@Casey95',
			},
		],
		'guarantor': [
			{
				'fullName': 'Susie Howe',
				'phone_number': '+1 (986) 431-2715',
				'email': 'susiehowe@portaline.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Augusta Frazier',
				'phone_number': '+1 (954) 506-2748',
				'email': 'augustafrazier@portaline.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Nunez Bryan',
				'phone_number': '+1 (956) 557-3665',
				'email': 'nunezbryan@portaline.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab4d09214b0dc2422e5',
		'profile_picture': 'https://picsum.photos/200/300?random=468',
		'organization': 'Lendsqr',
		'username': 'Marquita60',
		'fullName': 'Kelly Gross',
		'email': 'kellygross@portaline.com',
		'date_joined': 'Feb 05, 2022 09:39 PM',
		'status': 'Active',
		'phone_number': '+1 (803) 538-3276',
		'acc_tier': 3,
		'acc_balance': 82541283,
		'acc_number': 81599148045,
		'bank_name': 'SUPREMIA',
		'bvn': 2222657685,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'kellygross@supremia.com',
		'monthly_income': 6190,
		'loan_repayment': 994.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Donna Humphrey',
			},
			{
				'platform': 'twitter',
				'handle': '@Jeanine50',
			},
			{
				'platform': 'instagram',
				'handle': '@Greta33',
			},
		],
		'guarantor': [
			{
				'fullName': 'Osborn Kirk',
				'phone_number': '+1 (876) 400-3019',
				'email': 'osbornkirk@supremia.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Jacquelyn Foley',
				'phone_number': '+1 (908) 582-3777',
				'email': 'jacquelynfoley@supremia.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Dominguez Fields',
				'phone_number': '+1 (988) 453-3432',
				'email': 'dominguezfields@supremia.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab4aa683461403617be',
		'profile_picture': 'https://picsum.photos/200/300?random=865',
		'organization': 'Lendstar',
		'username': 'Price66',
		'fullName': 'Misty Booker',
		'email': 'mistybooker@supremia.com',
		'date_joined': 'Jul 27, 2021 06:01 PM',
		'status': 'Active',
		'phone_number': '+1 (875) 432-3859',
		'acc_tier': 2,
		'acc_balance': 87678056,
		'acc_number': 54845663712,
		'bank_name': 'ZENSUS',
		'bvn': 2222670778,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'mistybooker@zensus.com',
		'monthly_income': 7970,
		'loan_repayment': 571.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Carey Alvarez',
			},
			{
				'platform': 'twitter',
				'handle': '@Lorene52',
			},
			{
				'platform': 'instagram',
				'handle': '@Betty85',
			},
		],
		'guarantor': [
			{
				'fullName': 'Diana Battle',
				'phone_number': '+1 (981) 521-2968',
				'email': 'dianabattle@zensus.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Jaclyn Slater',
				'phone_number': '+1 (820) 555-3236',
				'email': 'jaclynslater@zensus.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Edwina Camacho',
				'phone_number': '+1 (873) 494-3491',
				'email': 'edwinacamacho@zensus.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab441c03790b0932954',
		'profile_picture': 'https://picsum.photos/200/300?random=193',
		'organization': 'Lendsqr',
		'username': 'Melanie43',
		'fullName': 'Winnie Dudley',
		'email': 'winniedudley@zensus.com',
		'date_joined': 'May 28, 2021 11:35 AM',
		'status': 'Inactive',
		'phone_number': '+1 (920) 549-3222',
		'acc_tier': 2,
		'acc_balance': 56648894,
		'acc_number': 24814362717,
		'bank_name': 'DENTREX',
		'bvn': 2222678487,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'winniedudley@dentrex.com',
		'monthly_income': 9880,
		'loan_repayment': 425.20000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Saundra Armstrong',
			},
			{
				'platform': 'twitter',
				'handle': '@Carr88',
			},
			{
				'platform': 'instagram',
				'handle': '@Evelyn94',
			},
		],
		'guarantor': [
			{
				'fullName': 'Strickland Olsen',
				'phone_number': '+1 (818) 564-3184',
				'email': 'stricklandolsen@dentrex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Deann Conner',
				'phone_number': '+1 (977) 407-2881',
				'email': 'deannconner@dentrex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Tanner Barton',
				'phone_number': '+1 (994) 440-2187',
				'email': 'tannerbarton@dentrex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab49b4c58183c52e597',
		'profile_picture': 'https://picsum.photos/200/300?random=24',
		'organization': 'Lendstar',
		'username': 'Rhodes63',
		'fullName': 'Mcdaniel Randall',
		'email': 'mcdanielrandall@dentrex.com',
		'date_joined': 'Jan 01, 2023 07:52 AM',
		'status': 'Pending',
		'phone_number': '+1 (980) 445-3858',
		'acc_tier': 2,
		'acc_balance': 61387847,
		'acc_number': 23669747346,
		'bank_name': 'HARMONEY',
		'bvn': 2222680213,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'mcdanielrandall@harmoney.com',
		'monthly_income': 9869,
		'loan_repayment': 855.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Rivera Tyler',
			},
			{
				'platform': 'twitter',
				'handle': '@Holder58',
			},
			{
				'platform': 'instagram',
				'handle': '@Angelique52',
			},
		],
		'guarantor': [
			{
				'fullName': 'Cassandra Crane',
				'phone_number': '+1 (874) 470-3748',
				'email': 'cassandracrane@harmoney.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Carson Morse',
				'phone_number': '+1 (885) 468-3653',
				'email': 'carsonmorse@harmoney.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Ines Mcbride',
				'phone_number': '+1 (951) 529-2511',
				'email': 'inesmcbride@harmoney.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e6ab491fb1fabaac3329d',
		'profile_picture': 'https://picsum.photos/200/300?random=860',
		'organization': 'Irorun',
		'username': 'Noelle74',
		'fullName': 'Conrad Reed',
		'email': 'conradreed@harmoney.com',
		'date_joined': 'Mar 20, 2021 09:13 AM',
		'status': 'Pending',
		'phone_number': '+1 (801) 409-2547',
		'acc_tier': 1,
		'acc_balance': 95073792,
		'acc_number': 79132456380,
		'bank_name': 'NURPLEX',
		'bvn': 2222695836,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'conradreed@nurplex.com',
		'monthly_income': 6069,
		'loan_repayment': 306.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Farrell Kerr',
			},
			{
				'platform': 'twitter',
				'handle': '@Mckenzie97',
			},
			{
				'platform': 'instagram',
				'handle': '@Buckley58',
			},
		],
		'guarantor': [
			{
				'fullName': 'Opal Holder',
				'phone_number': '+1 (884) 400-3517',
				'email': 'opalholder@nurplex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Prince Cook',
				'phone_number': '+1 (829) 568-2490',
				'email': 'princecook@nurplex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Madge Clements',
				'phone_number': '+1 (971) 455-3450',
				'email': 'madgeclements@nurplex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e6ab48cf91531f7822bf2',
		'profile_picture': 'https://picsum.photos/200/300?random=935',
		'organization': 'Lendstar',
		'username': 'Bauer44',
		'fullName': 'Alberta Robbins',
		'email': 'albertarobbins@nurplex.com',
		'date_joined': 'Aug 19, 2022 01:16 AM',
		'status': 'Pending',
		'phone_number': '+1 (999) 429-2464',
		'acc_tier': 2,
		'acc_balance': 31333267,
		'acc_number': 61700165670,
		'bank_name': 'FLUMBO',
		'bvn': 2222671297,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'albertarobbins@flumbo.com',
		'monthly_income': 6487,
		'loan_repayment': 319.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Benjamin Dennis',
			},
			{
				'platform': 'twitter',
				'handle': '@Celeste60',
			},
			{
				'platform': 'instagram',
				'handle': '@Riddle35',
			},
		],
		'guarantor': [
			{
				'fullName': 'Hensley Sanford',
				'phone_number': '+1 (959) 490-3739',
				'email': 'hensleysanford@flumbo.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Sheila Hayden',
				'phone_number': '+1 (870) 598-3066',
				'email': 'sheilahayden@flumbo.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Tanya Suarez',
				'phone_number': '+1 (957) 466-3981',
				'email': 'tanyasuarez@flumbo.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4f025a63ab8b37bdc',
		'profile_picture': 'https://picsum.photos/200/300?random=529',
		'organization': 'Lendsqr',
		'username': 'Myrna70',
		'fullName': 'Andrews Jarvis',
		'email': 'andrewsjarvis@flumbo.com',
		'date_joined': 'May 23, 2021 07:55 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (910) 485-2501',
		'acc_tier': 1,
		'acc_balance': 54539736,
		'acc_number': 9925591649,
		'bank_name': 'SUREPLEX',
		'bvn': 2222668407,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'andrewsjarvis@sureplex.com',
		'monthly_income': 5106,
		'loan_repayment': 886.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Owen Hoffman',
			},
			{
				'platform': 'twitter',
				'handle': '@Foreman76',
			},
			{
				'platform': 'instagram',
				'handle': '@Anne49',
			},
		],
		'guarantor': [
			{
				'fullName': 'Sanford Young',
				'phone_number': '+1 (860) 416-3848',
				'email': 'sanfordyoung@sureplex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Phelps Lester',
				'phone_number': '+1 (974) 520-2030',
				'email': 'phelpslester@sureplex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Jill Scott',
				'phone_number': '+1 (882) 534-2496',
				'email': 'jillscott@sureplex.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e6ab4cf3ea656c0ad09b0',
		'profile_picture': 'https://picsum.photos/200/300?random=431',
		'organization': 'Lendstar',
		'username': 'Latoya92',
		'fullName': 'Garner Grimes',
		'email': 'garnergrimes@sureplex.com',
		'date_joined': 'Sep 26, 2022 08:18 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (961) 429-3724',
		'acc_tier': 2,
		'acc_balance': 33407580,
		'acc_number': 15525688605,
		'bank_name': 'KONGENE',
		'bvn': 2222673678,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'garnergrimes@kongene.com',
		'monthly_income': 5698,
		'loan_repayment': 516.4,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Hampton Dunlap',
			},
			{
				'platform': 'twitter',
				'handle': '@Alana69',
			},
			{
				'platform': 'instagram',
				'handle': '@Newman77',
			},
		],
		'guarantor': [
			{
				'fullName': 'Trudy Petty',
				'phone_number': '+1 (897) 427-2100',
				'email': 'trudypetty@kongene.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Rose Neal',
				'phone_number': '+1 (973) 487-2642',
				'email': 'roseneal@kongene.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Crane Joyner',
				'phone_number': '+1 (814) 445-3246',
				'email': 'cranejoyner@kongene.com',
				'relationship': 'Friend',
			},
		],
	},
];
