import { CardProps, UserProps } from '../interfaces/typings';

export const cardDetails: CardProps[] = [
	{
		id: 1,
		icon: '/assets/icons/users/users.png',
		title: 'users',
		amount: 2453,
	},
	{
		id: 2,
		icon: '/assets/icons/users/active_users.png',
		title: 'active users',
		amount: 2453,
	},
	{
		id: 3,
		icon: '/assets/icons/users/loan_users.png',
		title: 'users with loans',
		amount: 12453,
	},
	{
		id: 4,
		icon: '/assets/icons/users/savings_users.png',
		title: 'users with savings',
		amount: 102453,
	},
];
export function formatNumber(number: number | null | undefined) {
	console.log(number);
	if (number == null || number == undefined) return;
	const numberString = number?.toString();
	return numberString?.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

export const admin = {
	id: 1,
	firstName: 'Ezekiel',
	lastName: 'Udiomuno',
	image: '/assets/images/user-image.jpg',
};

export const userTabs = ['General Details', 'Documents', 'Bank Details', 'Loans', 'Savings', 'App and System'];
export const tableHeaders = ['organization', 'username', 'email', 'phone number', 'date joined', 'status'];

export const usersData: UserProps[] = [
	{
		'id': '655088e656ea92b8bc1a4853',
		'profile_picture': 'https://picsum.photos/200/300?random=113',
		'organization': 'Irorun',
		'username': 'Whitley63',
		'fullName': 'Yang Gentry',
		'email': 'yanggentry@enquility.com',
		'date_joined': 'Dec 21, 2022 10:08 AM',
		'status': 'Pending',
		'phone_number': '+1 (938) 547-2457',
		'acc_tier': 2,
		'acc_balance': 62167790,
		'acc_number': 54851506514,
		'bank_name': 'MAXIMIND',
		'bvn': 2222666187,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'yanggentry@maximind.com',
		'monthly_income': {
			'min': 6832,
			'max': 10000,
		},
		'loan_repayment': 727.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Underwood Camacho',
			},
			{
				'platform': 'twitter',
				'handle': '@Dennis57',
			},
			{
				'platform': 'instagram',
				'handle': '@Nita72',
			},
		],
		'guarantor': [
			{
				'fullName': 'Foley Booth',
				'phone_number': '+1 (884) 566-3862',
				'email': 'foleybooth@maximind.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Luisa Mcmahon',
				'phone_number': '+1 (934) 558-3054',
				'email': 'luisamcmahon@maximind.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Gray Wells',
				'phone_number': '+1 (990) 519-3145',
				'email': 'graywells@maximind.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e614e0a7fb0c345a4e',
		'profile_picture': 'https://picsum.photos/200/300?random=65',
		'organization': 'Lendsqr',
		'username': 'Tracey52',
		'fullName': 'Nina Haley',
		'email': 'ninahaley@maximind.com',
		'date_joined': 'Jun 07, 2021 01:39 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (803) 593-3060',
		'acc_tier': 2,
		'acc_balance': 98307767,
		'acc_number': 39561827187,
		'bank_name': 'GAZAK',
		'bvn': 2222661221,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'ninahaley@gazak.com',
		'monthly_income': {
			'min': 3048,
			'max': 10000,
		},
		'loan_repayment': 389,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Walter Gray',
			},
			{
				'platform': 'twitter',
				'handle': '@Kaitlin50',
			},
			{
				'platform': 'instagram',
				'handle': '@Audra51',
			},
		],
		'guarantor': [
			{
				'fullName': 'Rose Davis',
				'phone_number': '+1 (981) 529-3634',
				'email': 'rosedavis@gazak.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Houston Poole',
				'phone_number': '+1 (843) 561-3845',
				'email': 'houstonpoole@gazak.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Wyatt Preston',
				'phone_number': '+1 (987) 486-2005',
				'email': 'wyattpreston@gazak.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e665ec0c133bc807c7',
		'profile_picture': 'https://picsum.photos/200/300?random=992',
		'organization': 'Irorun',
		'username': 'Justice43',
		'fullName': 'Greta Barrett',
		'email': 'gretabarrett@gazak.com',
		'date_joined': 'Oct 02, 2020 07:17 PM',
		'status': 'Inactive',
		'phone_number': '+1 (817) 509-3827',
		'acc_tier': 2,
		'acc_balance': 53000641,
		'acc_number': 27688131776,
		'bank_name': 'SQUISH',
		'bvn': 2222667308,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'gretabarrett@squish.com',
		'monthly_income': {
			'min': 3769,
			'max': 10000,
		},
		'loan_repayment': 456.20000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Susan Bender',
			},
			{
				'platform': 'twitter',
				'handle': '@Young79',
			},
			{
				'platform': 'instagram',
				'handle': '@Atkins80',
			},
		],
		'guarantor': [
			{
				'fullName': 'Haney House',
				'phone_number': '+1 (834) 591-3211',
				'email': 'haneyhouse@squish.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Robert Beard',
				'phone_number': '+1 (844) 436-3972',
				'email': 'robertbeard@squish.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lydia Wiggins',
				'phone_number': '+1 (912) 400-3250',
				'email': 'lydiawiggins@squish.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6cece6196510a3cec',
		'profile_picture': 'https://picsum.photos/200/300?random=739',
		'organization': 'Irorun',
		'username': 'Swanson33',
		'fullName': 'Clayton Cherry',
		'email': 'claytoncherry@squish.com',
		'date_joined': 'Mar 11, 2022 07:20 AM',
		'status': 'Inactive',
		'phone_number': '+1 (961) 504-2364',
		'acc_tier': 3,
		'acc_balance': 53104092,
		'acc_number': 26103580402,
		'bank_name': 'UPLINX',
		'bvn': 2222689386,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'claytoncherry@uplinx.com',
		'monthly_income': {
			'min': 4207,
			'max': 10000,
		},
		'loan_repayment': 333.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Baird Mendoza',
			},
			{
				'platform': 'twitter',
				'handle': '@Robbie74',
			},
			{
				'platform': 'instagram',
				'handle': '@Ruthie39',
			},
		],
		'guarantor': [
			{
				'fullName': 'Winters Bentley',
				'phone_number': '+1 (966) 492-3453',
				'email': 'wintersbentley@uplinx.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Lowery Moreno',
				'phone_number': '+1 (868) 598-2238',
				'email': 'lowerymoreno@uplinx.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Jewel Byrd',
				'phone_number': '+1 (826) 587-3620',
				'email': 'jewelbyrd@uplinx.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6572e169a10bdf967',
		'profile_picture': 'https://picsum.photos/200/300?random=52',
		'organization': 'Lendstar',
		'username': 'Bradshaw69',
		'fullName': 'Marcie Mcdaniel',
		'email': 'marciemcdaniel@uplinx.com',
		'date_joined': 'Jun 09, 2023 09:43 AM',
		'status': 'Inactive',
		'phone_number': '+1 (968) 590-3342',
		'acc_tier': 1,
		'acc_balance': 84189813,
		'acc_number': 55296898999,
		'bank_name': 'DATAGEN',
		'bvn': 2222676485,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'marciemcdaniel@datagen.com',
		'monthly_income': {
			'min': 4651,
			'max': 10000,
		},
		'loan_repayment': 854.9000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Elvia Mccall',
			},
			{
				'platform': 'twitter',
				'handle': '@Cole86',
			},
			{
				'platform': 'instagram',
				'handle': '@Glover93',
			},
		],
		'guarantor': [
			{
				'fullName': 'Robinson Rasmussen',
				'phone_number': '+1 (822) 599-2880',
				'email': 'robinsonrasmussen@datagen.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Sellers Garcia',
				'phone_number': '+1 (931) 405-3766',
				'email': 'sellersgarcia@datagen.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Kayla Finch',
				'phone_number': '+1 (918) 558-3966',
				'email': 'kaylafinch@datagen.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6dff10b0cb6a6e2e5',
		'profile_picture': 'https://picsum.photos/200/300?random=520',
		'organization': 'Lendstar',
		'username': 'Monique58',
		'fullName': 'Cathleen Joyce',
		'email': 'cathleenjoyce@datagen.com',
		'date_joined': 'Feb 28, 2021 07:12 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (916) 466-2571',
		'acc_tier': 1,
		'acc_balance': 83858974,
		'acc_number': 17277505729,
		'bank_name': 'DENTREX',
		'bvn': 2222670184,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'cathleenjoyce@dentrex.com',
		'monthly_income': {
			'min': 8554,
			'max': 10000,
		},
		'loan_repayment': 433.70000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Craig Sosa',
			},
			{
				'platform': 'twitter',
				'handle': '@England79',
			},
			{
				'platform': 'instagram',
				'handle': '@Corinne53',
			},
		],
		'guarantor': [
			{
				'fullName': 'Anthony Lester',
				'phone_number': '+1 (938) 476-2820',
				'email': 'anthonylester@dentrex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Charles Sandoval',
				'phone_number': '+1 (993) 585-2029',
				'email': 'charlessandoval@dentrex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Crosby Schwartz',
				'phone_number': '+1 (990) 461-3050',
				'email': 'crosbyschwartz@dentrex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6fa6ba691f3586dc6',
		'profile_picture': 'https://picsum.photos/200/300?random=552',
		'organization': 'Lendstar',
		'username': 'Burch43',
		'fullName': 'George Watts',
		'email': 'georgewatts@dentrex.com',
		'date_joined': 'Aug 19, 2021 09:07 AM',
		'status': 'Inactive',
		'phone_number': '+1 (892) 539-3595',
		'acc_tier': 3,
		'acc_balance': 48594992,
		'acc_number': 19001693362,
		'bank_name': 'BIOTICA',
		'bvn': 2222697004,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'georgewatts@biotica.com',
		'monthly_income': {
			'min': 3783,
			'max': 10000,
		},
		'loan_repayment': 796.7,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Kerri Fitzpatrick',
			},
			{
				'platform': 'twitter',
				'handle': '@Allison43',
			},
			{
				'platform': 'instagram',
				'handle': '@Bobbi76',
			},
		],
		'guarantor': [
			{
				'fullName': 'Allyson Lucas',
				'phone_number': '+1 (959) 475-3605',
				'email': 'allysonlucas@biotica.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Duke Conway',
				'phone_number': '+1 (859) 576-3518',
				'email': 'dukeconway@biotica.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Walters Odom',
				'phone_number': '+1 (961) 418-2257',
				'email': 'waltersodom@biotica.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e68880ff275510a81f',
		'profile_picture': 'https://picsum.photos/200/300?random=266',
		'organization': 'Lendsqr',
		'username': 'Sheena42',
		'fullName': 'Kathleen Webster',
		'email': 'kathleenwebster@biotica.com',
		'date_joined': 'Feb 15, 2022 08:04 PM',
		'status': 'Inactive',
		'phone_number': '+1 (960) 551-3579',
		'acc_tier': 1,
		'acc_balance': 667795,
		'acc_number': 66294429845,
		'bank_name': 'WARETEL',
		'bvn': 2222691309,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'kathleenwebster@waretel.com',
		'monthly_income': {
			'min': 5374,
			'max': 10000,
		},
		'loan_repayment': 432.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Alba Blake',
			},
			{
				'platform': 'twitter',
				'handle': '@Aurelia33',
			},
			{
				'platform': 'instagram',
				'handle': '@Cecelia52',
			},
		],
		'guarantor': [
			{
				'fullName': 'Mcdowell Molina',
				'phone_number': '+1 (928) 418-2682',
				'email': 'mcdowellmolina@waretel.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Butler Bray',
				'phone_number': '+1 (998) 424-3889',
				'email': 'butlerbray@waretel.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Frederick Fletcher',
				'phone_number': '+1 (812) 502-3975',
				'email': 'frederickfletcher@waretel.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6db66cd43a5406165',
		'profile_picture': 'https://picsum.photos/200/300?random=474',
		'organization': 'Irorun',
		'username': 'Susie40',
		'fullName': 'Heather Stark',
		'email': 'heatherstark@waretel.com',
		'date_joined': 'Mar 14, 2022 07:25 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (967) 456-2726',
		'acc_tier': 2,
		'acc_balance': 77737893,
		'acc_number': 32021088190,
		'bank_name': 'NIKUDA',
		'bvn': 2222688616,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'heatherstark@nikuda.com',
		'monthly_income': {
			'min': 6221,
			'max': 10000,
		},
		'loan_repayment': 454.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Zamora Lindsey',
			},
			{
				'platform': 'twitter',
				'handle': '@Wall97',
			},
			{
				'platform': 'instagram',
				'handle': '@Mccray68',
			},
		],
		'guarantor': [
			{
				'fullName': 'Snow Alford',
				'phone_number': '+1 (882) 430-3406',
				'email': 'snowalford@nikuda.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Cantrell Benson',
				'phone_number': '+1 (960) 444-2008',
				'email': 'cantrellbenson@nikuda.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Pamela Craig',
				'phone_number': '+1 (947) 560-3664',
				'email': 'pamelacraig@nikuda.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6bd19a50223918a19',
		'profile_picture': 'https://picsum.photos/200/300?random=639',
		'organization': 'Lendstar',
		'username': 'Hubbard53',
		'fullName': 'June Atkinson',
		'email': 'juneatkinson@nikuda.com',
		'date_joined': 'Feb 12, 2023 10:45 PM',
		'status': 'Inactive',
		'phone_number': '+1 (917) 452-3337',
		'acc_tier': 1,
		'acc_balance': 1769196,
		'acc_number': 58565857101,
		'bank_name': 'IRACK',
		'bvn': 2222676703,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'juneatkinson@irack.com',
		'monthly_income': {
			'min': 9438,
			'max': 10000,
		},
		'loan_repayment': 839.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Stein Hartman',
			},
			{
				'platform': 'twitter',
				'handle': '@Gutierrez65',
			},
			{
				'platform': 'instagram',
				'handle': '@Armstrong60',
			},
		],
		'guarantor': [
			{
				'fullName': 'Bryan Barnes',
				'phone_number': '+1 (919) 564-3493',
				'email': 'bryanbarnes@irack.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Holt Albert',
				'phone_number': '+1 (968) 400-3064',
				'email': 'holtalbert@irack.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Isabella Bond',
				'phone_number': '+1 (944) 507-3070',
				'email': 'isabellabond@irack.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e639bf04af4bcba231',
		'profile_picture': 'https://picsum.photos/200/300?random=718',
		'organization': 'Lendstar',
		'username': 'Hays33',
		'fullName': 'Hogan Cote',
		'email': 'hogancote@irack.com',
		'date_joined': 'Aug 14, 2021 04:02 PM',
		'status': 'Inactive',
		'phone_number': '+1 (864) 557-2800',
		'acc_tier': 1,
		'acc_balance': 26321388,
		'acc_number': 63851197765,
		'bank_name': 'IZZBY',
		'bvn': 2222667085,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'hogancote@izzby.com',
		'monthly_income': {
			'min': 8488,
			'max': 10000,
		},
		'loan_repayment': 721.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Lane Dominguez',
			},
			{
				'platform': 'twitter',
				'handle': '@Imogene77',
			},
			{
				'platform': 'instagram',
				'handle': '@Jennifer98',
			},
		],
		'guarantor': [
			{
				'fullName': 'Estelle Palmer',
				'phone_number': '+1 (940) 474-3224',
				'email': 'estellepalmer@izzby.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Maxwell Macias',
				'phone_number': '+1 (829) 537-3086',
				'email': 'maxwellmacias@izzby.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Kitty Ingram',
				'phone_number': '+1 (892) 481-2887',
				'email': 'kittyingram@izzby.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e623b7ce93c972ecb6',
		'profile_picture': 'https://picsum.photos/200/300?random=628',
		'organization': 'Irorun',
		'username': 'Bowen93',
		'fullName': 'Ellison Fowler',
		'email': 'ellisonfowler@izzby.com',
		'date_joined': 'Nov 20, 2020 12:36 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (926) 593-3823',
		'acc_tier': 1,
		'acc_balance': 92452314,
		'acc_number': 48277058452,
		'bank_name': 'FROLIX',
		'bvn': 2222660160,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'ellisonfowler@frolix.com',
		'monthly_income': {
			'min': 9134,
			'max': 10000,
		},
		'loan_repayment': 928.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Araceli Slater',
			},
			{
				'platform': 'twitter',
				'handle': '@Isabel98',
			},
			{
				'platform': 'instagram',
				'handle': '@Mcgowan78',
			},
		],
		'guarantor': [
			{
				'fullName': 'Minnie Cruz',
				'phone_number': '+1 (856) 414-2898',
				'email': 'minniecruz@frolix.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Lula Lawrence',
				'phone_number': '+1 (874) 407-2181',
				'email': 'lulalawrence@frolix.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lakeisha Morse',
				'phone_number': '+1 (976) 571-2351',
				'email': 'lakeishamorse@frolix.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e630b7bb06fe45dbe1',
		'profile_picture': 'https://picsum.photos/200/300?random=478',
		'organization': 'Lendstar',
		'username': 'Golden73',
		'fullName': 'Salinas Miller',
		'email': 'salinasmiller@frolix.com',
		'date_joined': 'Dec 05, 2020 12:28 AM',
		'status': 'Active',
		'phone_number': '+1 (864) 418-2842',
		'acc_tier': 1,
		'acc_balance': 43585970,
		'acc_number': 27252958587,
		'bank_name': 'KLUGGER',
		'bvn': 2222676023,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'salinasmiller@klugger.com',
		'monthly_income': {
			'min': 6722,
			'max': 10000,
		},
		'loan_repayment': 641,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Rocha Oneill',
			},
			{
				'platform': 'twitter',
				'handle': '@Ellen97',
			},
			{
				'platform': 'instagram',
				'handle': '@Gonzales45',
			},
		],
		'guarantor': [
			{
				'fullName': 'Brandie Harper',
				'phone_number': '+1 (802) 518-2512',
				'email': 'brandieharper@klugger.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Leticia Grant',
				'phone_number': '+1 (801) 566-3108',
				'email': 'leticiagrant@klugger.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Knapp Mcintyre',
				'phone_number': '+1 (887) 552-3267',
				'email': 'knappmcintyre@klugger.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6a6ea7b05c263cda9',
		'profile_picture': 'https://picsum.photos/200/300?random=291',
		'organization': 'Lendsqr',
		'username': 'Reilly90',
		'fullName': 'Milagros Doyle',
		'email': 'milagrosdoyle@klugger.com',
		'date_joined': 'Jan 05, 2020 10:29 AM',
		'status': 'Pending',
		'phone_number': '+1 (974) 577-3538',
		'acc_tier': 3,
		'acc_balance': 24410406,
		'acc_number': 27759601897,
		'bank_name': 'GEEKUS',
		'bvn': 2222659801,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'milagrosdoyle@geekus.com',
		'monthly_income': {
			'min': 3556,
			'max': 10000,
		},
		'loan_repayment': 401.20000000000005,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Teresa Taylor',
			},
			{
				'platform': 'twitter',
				'handle': '@Green81',
			},
			{
				'platform': 'instagram',
				'handle': '@Keith63',
			},
		],
		'guarantor': [
			{
				'fullName': 'Dianne Rhodes',
				'phone_number': '+1 (854) 421-2844',
				'email': 'diannerhodes@geekus.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Farrell Owen',
				'phone_number': '+1 (804) 410-2404',
				'email': 'farrellowen@geekus.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Elnora Turner',
				'phone_number': '+1 (907) 513-3939',
				'email': 'elnoraturner@geekus.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e61f88a33510637229',
		'profile_picture': 'https://picsum.photos/200/300?random=419',
		'organization': 'Lendsqr',
		'username': 'Kimberley35',
		'fullName': 'Gomez Carr',
		'email': 'gomezcarr@geekus.com',
		'date_joined': 'Feb 14, 2020 10:51 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (872) 405-2148',
		'acc_tier': 1,
		'acc_balance': 60868843,
		'acc_number': 43956606864,
		'bank_name': 'AQUASSEUR',
		'bvn': 2222683436,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'gomezcarr@aquasseur.com',
		'monthly_income': {
			'min': 3425,
			'max': 10000,
		},
		'loan_repayment': 982,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Garcia Lowe',
			},
			{
				'platform': 'twitter',
				'handle': '@Lindsay58',
			},
			{
				'platform': 'instagram',
				'handle': '@Winifred32',
			},
		],
		'guarantor': [
			{
				'fullName': 'Gillespie Barker',
				'phone_number': '+1 (936) 588-2552',
				'email': 'gillespiebarker@aquasseur.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Hinton Todd',
				'phone_number': '+1 (911) 471-2838',
				'email': 'hintontodd@aquasseur.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Brittney Savage',
				'phone_number': '+1 (857) 521-2726',
				'email': 'brittneysavage@aquasseur.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e67139ce6f618fd05a',
		'profile_picture': 'https://picsum.photos/200/300?random=574',
		'organization': 'Lendstar',
		'username': 'Miranda65',
		'fullName': 'Mindy Durham',
		'email': 'mindydurham@aquasseur.com',
		'date_joined': 'Sep 09, 2022 12:15 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (839) 416-3655',
		'acc_tier': 2,
		'acc_balance': 37361430,
		'acc_number': 67567906840,
		'bank_name': 'COGENTRY',
		'bvn': 2222689335,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'mindydurham@cogentry.com',
		'monthly_income': {
			'min': 5358,
			'max': 10000,
		},
		'loan_repayment': 912.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Gena Harrington',
			},
			{
				'platform': 'twitter',
				'handle': '@Obrien34',
			},
			{
				'platform': 'instagram',
				'handle': '@Henson84',
			},
		],
		'guarantor': [
			{
				'fullName': 'Kane Hoffman',
				'phone_number': '+1 (839) 491-3852',
				'email': 'kanehoffman@cogentry.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Raquel Benton',
				'phone_number': '+1 (986) 428-3106',
				'email': 'raquelbenton@cogentry.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Marietta Ball',
				'phone_number': '+1 (873) 597-3274',
				'email': 'mariettaball@cogentry.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e667aad153ed918ebd',
		'profile_picture': 'https://picsum.photos/200/300?random=226',
		'organization': 'Lendstar',
		'username': 'Chandler73',
		'fullName': 'Jane Harmon',
		'email': 'janeharmon@cogentry.com',
		'date_joined': 'Nov 12, 2023 12:28 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (941) 441-3477',
		'acc_tier': 2,
		'acc_balance': 86226942,
		'acc_number': 46907716214,
		'bank_name': 'SEQUITUR',
		'bvn': 2222661742,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'janeharmon@sequitur.com',
		'monthly_income': {
			'min': 4585,
			'max': 10000,
		},
		'loan_repayment': 573.4,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Jeannine Herring',
			},
			{
				'platform': 'twitter',
				'handle': '@Kaye95',
			},
			{
				'platform': 'instagram',
				'handle': '@Lara89',
			},
		],
		'guarantor': [
			{
				'fullName': 'Lina Fuller',
				'phone_number': '+1 (914) 423-2526',
				'email': 'linafuller@sequitur.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Farley Carver',
				'phone_number': '+1 (903) 553-2206',
				'email': 'farleycarver@sequitur.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Tara Davenport',
				'phone_number': '+1 (945) 457-2431',
				'email': 'taradavenport@sequitur.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e660992c93d9da8e62',
		'profile_picture': 'https://picsum.photos/200/300?random=7',
		'organization': 'Lendsqr',
		'username': 'Ballard78',
		'fullName': 'Diaz Murphy',
		'email': 'diazmurphy@sequitur.com',
		'date_joined': 'Feb 11, 2020 03:12 PM',
		'status': 'Inactive',
		'phone_number': '+1 (847) 451-2638',
		'acc_tier': 3,
		'acc_balance': 71924068,
		'acc_number': 70093027344,
		'bank_name': 'MARKETOID',
		'bvn': 2222698818,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'diazmurphy@marketoid.com',
		'monthly_income': {
			'min': 4963,
			'max': 10000,
		},
		'loan_repayment': 484.90000000000003,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Cheryl Carter',
			},
			{
				'platform': 'twitter',
				'handle': '@Lorraine43',
			},
			{
				'platform': 'instagram',
				'handle': '@Howe58',
			},
		],
		'guarantor': [
			{
				'fullName': 'Claudia Hancock',
				'phone_number': '+1 (997) 595-2250',
				'email': 'claudiahancock@marketoid.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Woodard Ayala',
				'phone_number': '+1 (878) 593-2812',
				'email': 'woodardayala@marketoid.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Stephenson Hardin',
				'phone_number': '+1 (844) 513-3919',
				'email': 'stephensonhardin@marketoid.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e66de6568bb6973554',
		'profile_picture': 'https://picsum.photos/200/300?random=301',
		'organization': 'Lendsqr',
		'username': 'Osborne45',
		'fullName': 'April Wilson',
		'email': 'aprilwilson@marketoid.com',
		'date_joined': 'Jan 01, 2023 02:14 AM',
		'status': 'Active',
		'phone_number': '+1 (865) 466-3588',
		'acc_tier': 1,
		'acc_balance': 64532357,
		'acc_number': 50020981511,
		'bank_name': 'COMBOT',
		'bvn': 2222661444,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'aprilwilson@combot.com',
		'monthly_income': {
			'min': 6059,
			'max': 10000,
		},
		'loan_repayment': 871.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Deloris Fry',
			},
			{
				'platform': 'twitter',
				'handle': '@Conrad41',
			},
			{
				'platform': 'instagram',
				'handle': '@Shannon85',
			},
		],
		'guarantor': [
			{
				'fullName': 'Wagner Hurley',
				'phone_number': '+1 (926) 466-2789',
				'email': 'wagnerhurley@combot.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Berger Goodman',
				'phone_number': '+1 (909) 526-2285',
				'email': 'bergergoodman@combot.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lolita Hull',
				'phone_number': '+1 (872) 463-3123',
				'email': 'lolitahull@combot.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6843bb3da2f68ed5b',
		'profile_picture': 'https://picsum.photos/200/300?random=722',
		'organization': 'Lendsqr',
		'username': 'Barber91',
		'fullName': 'Faye Sweeney',
		'email': 'fayesweeney@combot.com',
		'date_joined': 'Sep 27, 2020 03:28 PM',
		'status': 'Pending',
		'phone_number': '+1 (826) 458-2954',
		'acc_tier': 2,
		'acc_balance': 72791187,
		'acc_number': 23670061764,
		'bank_name': 'AFFLUEX',
		'bvn': 2222696932,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'fayesweeney@affluex.com',
		'monthly_income': {
			'min': 8095,
			'max': 10000,
		},
		'loan_repayment': 574.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Abigail Parker',
			},
			{
				'platform': 'twitter',
				'handle': '@Nell65',
			},
			{
				'platform': 'instagram',
				'handle': '@Matilda51',
			},
		],
		'guarantor': [
			{
				'fullName': 'Luna Banks',
				'phone_number': '+1 (998) 504-2722',
				'email': 'lunabanks@affluex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Travis Valenzuela',
				'phone_number': '+1 (809) 452-3149',
				'email': 'travisvalenzuela@affluex.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Lewis Cleveland',
				'phone_number': '+1 (963) 528-3796',
				'email': 'lewiscleveland@affluex.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6096ee5707a6e6710',
		'profile_picture': 'https://picsum.photos/200/300?random=113',
		'organization': 'Irorun',
		'username': 'Jeanie90',
		'fullName': 'Dale Hensley',
		'email': 'dalehensley@affluex.com',
		'date_joined': 'Feb 22, 2022 03:25 PM',
		'status': 'Pending',
		'phone_number': '+1 (960) 427-2650',
		'acc_tier': 2,
		'acc_balance': 51277844,
		'acc_number': 56469352837,
		'bank_name': 'OBLIQ',
		'bvn': 2222669920,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'dalehensley@obliq.com',
		'monthly_income': {
			'min': 8458,
			'max': 10000,
		},
		'loan_repayment': 996.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Elliott Dunn',
			},
			{
				'platform': 'twitter',
				'handle': '@Payne83',
			},
			{
				'platform': 'instagram',
				'handle': '@Amy67',
			},
		],
		'guarantor': [
			{
				'fullName': 'Sweeney Fitzgerald',
				'phone_number': '+1 (835) 512-3282',
				'email': 'sweeneyfitzgerald@obliq.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Lynch Michael',
				'phone_number': '+1 (821) 467-3689',
				'email': 'lynchmichael@obliq.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Townsend Hawkins',
				'phone_number': '+1 (854) 468-2611',
				'email': 'townsendhawkins@obliq.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e60220b10d1ee7b8f3',
		'profile_picture': 'https://picsum.photos/200/300?random=361',
		'organization': 'Irorun',
		'username': 'Allie98',
		'fullName': 'Melva Barr',
		'email': 'melvabarr@obliq.com',
		'date_joined': 'Feb 07, 2022 08:31 AM',
		'status': 'Active',
		'phone_number': '+1 (934) 476-2068',
		'acc_tier': 1,
		'acc_balance': 70735306,
		'acc_number': 64407215629,
		'bank_name': 'ANIMALIA',
		'bvn': 2222664293,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'melvabarr@animalia.com',
		'monthly_income': {
			'min': 5366,
			'max': 10000,
		},
		'loan_repayment': 423.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Georgette Combs',
			},
			{
				'platform': 'twitter',
				'handle': '@Bean66',
			},
			{
				'platform': 'instagram',
				'handle': '@Ronda85',
			},
		],
		'guarantor': [
			{
				'fullName': 'Marsha Kent',
				'phone_number': '+1 (915) 434-3820',
				'email': 'marshakent@animalia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Gilliam Casey',
				'phone_number': '+1 (916) 403-2921',
				'email': 'gilliamcasey@animalia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Boyer Shaffer',
				'phone_number': '+1 (841) 508-3697',
				'email': 'boyershaffer@animalia.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6600d6762ba6333f3',
		'profile_picture': 'https://picsum.photos/200/300?random=798',
		'organization': 'Irorun',
		'username': 'Della83',
		'fullName': 'Vega Barry',
		'email': 'vegabarry@animalia.com',
		'date_joined': 'Jan 17, 2022 07:57 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (818) 578-2148',
		'acc_tier': 2,
		'acc_balance': 75925548,
		'acc_number': 60028996838,
		'bank_name': 'ENDICIL',
		'bvn': 2222666448,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'vegabarry@endicil.com',
		'monthly_income': {
			'min': 5558,
			'max': 10000,
		},
		'loan_repayment': 600.8000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Carney Kaufman',
			},
			{
				'platform': 'twitter',
				'handle': '@Louise66',
			},
			{
				'platform': 'instagram',
				'handle': '@Dolores44',
			},
		],
		'guarantor': [
			{
				'fullName': 'Lynn Holder',
				'phone_number': '+1 (942) 412-3442',
				'email': 'lynnholder@endicil.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Rene Bennett',
				'phone_number': '+1 (982) 506-3897',
				'email': 'renebennett@endicil.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Traci Roman',
				'phone_number': '+1 (914) 515-3099',
				'email': 'traciroman@endicil.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e66ef5f4c2a5ac5f9d',
		'profile_picture': 'https://picsum.photos/200/300?random=189',
		'organization': 'Lendstar',
		'username': 'Kendra59',
		'fullName': 'Ethel Bowman',
		'email': 'ethelbowman@endicil.com',
		'date_joined': 'May 16, 2021 04:28 PM',
		'status': 'Pending',
		'phone_number': '+1 (968) 520-3749',
		'acc_tier': 1,
		'acc_balance': 5484473,
		'acc_number': 48098444402,
		'bank_name': 'CAXT',
		'bvn': 2222699851,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'ethelbowman@caxt.com',
		'monthly_income': {
			'min': 8509,
			'max': 10000,
		},
		'loan_repayment': 524,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Brewer Herrera',
			},
			{
				'platform': 'twitter',
				'handle': '@Davidson52',
			},
			{
				'platform': 'instagram',
				'handle': '@Wendy72',
			},
		],
		'guarantor': [
			{
				'fullName': 'Jimenez Whitaker',
				'phone_number': '+1 (966) 500-2397',
				'email': 'jimenezwhitaker@caxt.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Ewing Bernard',
				'phone_number': '+1 (928) 592-3039',
				'email': 'ewingbernard@caxt.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lynda Sanders',
				'phone_number': '+1 (837) 555-2417',
				'email': 'lyndasanders@caxt.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e617969f387c57edad',
		'profile_picture': 'https://picsum.photos/200/300?random=8',
		'organization': 'Irorun',
		'username': 'Simon33',
		'fullName': 'Summer Hale',
		'email': 'summerhale@caxt.com',
		'date_joined': 'Sep 10, 2021 05:14 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (913) 555-2843',
		'acc_tier': 1,
		'acc_balance': 14543347,
		'acc_number': 44771696235,
		'bank_name': 'ISOTERNIA',
		'bvn': 2222670999,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'summerhale@isoternia.com',
		'monthly_income': {
			'min': 4527,
			'max': 10000,
		},
		'loan_repayment': 748.9000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Jenny Small',
			},
			{
				'platform': 'twitter',
				'handle': '@Marcy84',
			},
			{
				'platform': 'instagram',
				'handle': '@Whitehead88',
			},
		],
		'guarantor': [
			{
				'fullName': 'Burt Pierce',
				'phone_number': '+1 (919) 502-2300',
				'email': 'burtpierce@isoternia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Maddox Cardenas',
				'phone_number': '+1 (857) 406-3024',
				'email': 'maddoxcardenas@isoternia.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Leonor Howell',
				'phone_number': '+1 (974) 473-3476',
				'email': 'leonorhowell@isoternia.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6208aa7e3245d2384',
		'profile_picture': 'https://picsum.photos/200/300?random=326',
		'organization': 'Lendstar',
		'username': 'Campos62',
		'fullName': 'Greer Fernandez',
		'email': 'greerfernandez@isoternia.com',
		'date_joined': 'Oct 29, 2021 08:48 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (996) 418-2508',
		'acc_tier': 3,
		'acc_balance': 67929045,
		'acc_number': 69633825805,
		'bank_name': 'CINCYR',
		'bvn': 2222684441,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'greerfernandez@cincyr.com',
		'monthly_income': {
			'min': 8877,
			'max': 10000,
		},
		'loan_repayment': 797.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Sutton Bolton',
			},
			{
				'platform': 'twitter',
				'handle': '@Justine55',
			},
			{
				'platform': 'instagram',
				'handle': '@Beck37',
			},
		],
		'guarantor': [
			{
				'fullName': 'Natalia Holloway',
				'phone_number': '+1 (807) 463-3289',
				'email': 'nataliaholloway@cincyr.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Marjorie Holland',
				'phone_number': '+1 (962) 404-3401',
				'email': 'marjorieholland@cincyr.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lawanda Phillips',
				'phone_number': '+1 (870) 512-3909',
				'email': 'lawandaphillips@cincyr.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6fccfde9cda98af52',
		'profile_picture': 'https://picsum.photos/200/300?random=392',
		'organization': 'Lendsqr',
		'username': 'Wells49',
		'fullName': 'Morrison Petty',
		'email': 'morrisonpetty@cincyr.com',
		'date_joined': 'Sep 21, 2023 01:03 PM',
		'status': 'Pending',
		'phone_number': '+1 (950) 559-2232',
		'acc_tier': 1,
		'acc_balance': 21295678,
		'acc_number': 38043616798,
		'bank_name': 'ZILPHUR',
		'bvn': 2222689010,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'morrisonpetty@zilphur.com',
		'monthly_income': {
			'min': 8410,
			'max': 10000,
		},
		'loan_repayment': 529.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Gayle Hanson',
			},
			{
				'platform': 'twitter',
				'handle': '@Landry56',
			},
			{
				'platform': 'instagram',
				'handle': '@Roslyn80',
			},
		],
		'guarantor': [
			{
				'fullName': 'Trisha Robinson',
				'phone_number': '+1 (950) 515-2211',
				'email': 'trisharobinson@zilphur.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Dodson Lambert',
				'phone_number': '+1 (952) 430-2280',
				'email': 'dodsonlambert@zilphur.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Rodgers Rose',
				'phone_number': '+1 (948) 419-3486',
				'email': 'rodgersrose@zilphur.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e69a8e5d81323dd740',
		'profile_picture': 'https://picsum.photos/200/300?random=499',
		'organization': 'Lendsqr',
		'username': 'Earnestine46',
		'fullName': 'Reynolds Thompson',
		'email': 'reynoldsthompson@zilphur.com',
		'date_joined': 'Aug 01, 2023 09:55 PM',
		'status': 'Inactive',
		'phone_number': '+1 (975) 536-3943',
		'acc_tier': 3,
		'acc_balance': 46695691,
		'acc_number': 23009366339,
		'bank_name': 'WEBIOTIC',
		'bvn': 2222685115,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'reynoldsthompson@webiotic.com',
		'monthly_income': {
			'min': 7137,
			'max': 10000,
		},
		'loan_repayment': 349.40000000000003,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Mccullough Charles',
			},
			{
				'platform': 'twitter',
				'handle': '@Agnes57',
			},
			{
				'platform': 'instagram',
				'handle': '@Sharp89',
			},
		],
		'guarantor': [
			{
				'fullName': 'Barlow Oliver',
				'phone_number': '+1 (990) 404-2155',
				'email': 'barlowoliver@webiotic.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Gross Calderon',
				'phone_number': '+1 (826) 444-2136',
				'email': 'grosscalderon@webiotic.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Josefina Odonnell',
				'phone_number': '+1 (949) 431-2351',
				'email': 'josefinaodonnell@webiotic.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6d079c519ca63adc0',
		'profile_picture': 'https://picsum.photos/200/300?random=901',
		'organization': 'Lendsqr',
		'username': 'Janet73',
		'fullName': 'Woods Gonzalez',
		'email': 'woodsgonzalez@webiotic.com',
		'date_joined': 'May 17, 2022 10:59 PM',
		'status': 'Pending',
		'phone_number': '+1 (998) 447-3772',
		'acc_tier': 2,
		'acc_balance': 8459396,
		'acc_number': 64051777297,
		'bank_name': 'TRIPSCH',
		'bvn': 2222657649,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'woodsgonzalez@tripsch.com',
		'monthly_income': {
			'min': 6553,
			'max': 10000,
		},
		'loan_repayment': 566.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Kathie Stafford',
			},
			{
				'platform': 'twitter',
				'handle': '@Moran66',
			},
			{
				'platform': 'instagram',
				'handle': '@Davenport36',
			},
		],
		'guarantor': [
			{
				'fullName': 'Joyner Abbott',
				'phone_number': '+1 (813) 523-3882',
				'email': 'joynerabbott@tripsch.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Patterson Raymond',
				'phone_number': '+1 (895) 438-2279',
				'email': 'pattersonraymond@tripsch.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Samantha Miles',
				'phone_number': '+1 (953) 413-3130',
				'email': 'samanthamiles@tripsch.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e610aab5c1aa5ef361',
		'profile_picture': 'https://picsum.photos/200/300?random=998',
		'organization': 'Lendstar',
		'username': 'Miriam60',
		'fullName': 'Jayne Rodgers',
		'email': 'jaynerodgers@tripsch.com',
		'date_joined': 'Feb 19, 2020 10:52 AM',
		'status': 'Pending',
		'phone_number': '+1 (986) 567-3462',
		'acc_tier': 2,
		'acc_balance': 57717081,
		'acc_number': 9540133290,
		'bank_name': 'PLASMOX',
		'bvn': 2222663434,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'jaynerodgers@plasmox.com',
		'monthly_income': {
			'min': 5579,
			'max': 10000,
		},
		'loan_repayment': 728.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Bettie Rice',
			},
			{
				'platform': 'twitter',
				'handle': '@Cassandra45',
			},
			{
				'platform': 'instagram',
				'handle': '@Freeman95',
			},
		],
		'guarantor': [
			{
				'fullName': 'Tillman Beach',
				'phone_number': '+1 (921) 537-3002',
				'email': 'tillmanbeach@plasmox.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Vicky Mayer',
				'phone_number': '+1 (973) 541-2631',
				'email': 'vickymayer@plasmox.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Jones Puckett',
				'phone_number': '+1 (871) 520-3283',
				'email': 'jonespuckett@plasmox.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6d728f0f3a9dd3b29',
		'profile_picture': 'https://picsum.photos/200/300?random=504',
		'organization': 'Lendsqr',
		'username': 'Eleanor70',
		'fullName': 'Dionne Pennington',
		'email': 'dionnepennington@plasmox.com',
		'date_joined': 'Aug 16, 2020 04:01 AM',
		'status': 'Active',
		'phone_number': '+1 (848) 473-2477',
		'acc_tier': 1,
		'acc_balance': 17513684,
		'acc_number': 36184704896,
		'bank_name': 'FOSSIEL',
		'bvn': 2222665160,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'dionnepennington@fossiel.com',
		'monthly_income': {
			'min': 9758,
			'max': 10000,
		},
		'loan_repayment': 964.4000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Sims Frye',
			},
			{
				'platform': 'twitter',
				'handle': '@Graves70',
			},
			{
				'platform': 'instagram',
				'handle': '@Lavonne45',
			},
		],
		'guarantor': [
			{
				'fullName': 'Meyer Mooney',
				'phone_number': '+1 (815) 538-3048',
				'email': 'meyermooney@fossiel.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Porter Weaver',
				'phone_number': '+1 (929) 508-3156',
				'email': 'porterweaver@fossiel.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Irma Knowles',
				'phone_number': '+1 (863) 507-2566',
				'email': 'irmaknowles@fossiel.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e62e675493db623205',
		'profile_picture': 'https://picsum.photos/200/300?random=360',
		'organization': 'Lendstar',
		'username': 'Mamie50',
		'fullName': 'Acevedo Park',
		'email': 'acevedopark@fossiel.com',
		'date_joined': 'Dec 08, 2020 02:14 PM',
		'status': 'Inactive',
		'phone_number': '+1 (813) 463-2550',
		'acc_tier': 3,
		'acc_balance': 90879147,
		'acc_number': 56403277826,
		'bank_name': 'IMMUNICS',
		'bvn': 2222687351,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'acevedopark@immunics.com',
		'monthly_income': {
			'min': 9828,
			'max': 10000,
		},
		'loan_repayment': 596.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Murray Cooke',
			},
			{
				'platform': 'twitter',
				'handle': '@Lambert66',
			},
			{
				'platform': 'instagram',
				'handle': '@Macdonald33',
			},
		],
		'guarantor': [
			{
				'fullName': 'Peters Lindsay',
				'phone_number': '+1 (975) 527-2683',
				'email': 'peterslindsay@immunics.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Dorthy Anderson',
				'phone_number': '+1 (855) 447-3102',
				'email': 'dorthyanderson@immunics.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Constance Valencia',
				'phone_number': '+1 (896) 429-2094',
				'email': 'constancevalencia@immunics.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6a6dc431af48d2edf',
		'profile_picture': 'https://picsum.photos/200/300?random=959',
		'organization': 'Lendsqr',
		'username': 'Vang43',
		'fullName': 'Dixon Lancaster',
		'email': 'dixonlancaster@immunics.com',
		'date_joined': 'Nov 28, 2021 11:08 PM',
		'status': 'Pending',
		'phone_number': '+1 (820) 558-3541',
		'acc_tier': 2,
		'acc_balance': 98351923,
		'acc_number': 84598519209,
		'bank_name': 'QUIZMO',
		'bvn': 2222670008,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'dixonlancaster@quizmo.com',
		'monthly_income': {
			'min': 6120,
			'max': 10000,
		},
		'loan_repayment': 699.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Alfreda Pickett',
			},
			{
				'platform': 'twitter',
				'handle': '@Eunice34',
			},
			{
				'platform': 'instagram',
				'handle': '@Knight32',
			},
		],
		'guarantor': [
			{
				'fullName': 'Lara Koch',
				'phone_number': '+1 (883) 485-2797',
				'email': 'larakoch@quizmo.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Maura Cabrera',
				'phone_number': '+1 (813) 544-3306',
				'email': 'mauracabrera@quizmo.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Sophie Chavez',
				'phone_number': '+1 (826) 485-3201',
				'email': 'sophiechavez@quizmo.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6f5979eabca3e700c',
		'profile_picture': 'https://picsum.photos/200/300?random=698',
		'organization': 'Irorun',
		'username': 'Richard75',
		'fullName': 'Consuelo Salinas',
		'email': 'consuelosalinas@quizmo.com',
		'date_joined': 'Apr 23, 2020 07:54 AM',
		'status': 'Active',
		'phone_number': '+1 (947) 484-3186',
		'acc_tier': 1,
		'acc_balance': 61191062,
		'acc_number': 21612169441,
		'bank_name': 'PUSHCART',
		'bvn': 2222677638,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'consuelosalinas@pushcart.com',
		'monthly_income': {
			'min': 7281,
			'max': 10000,
		},
		'loan_repayment': 912.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Twila Vaughn',
			},
			{
				'platform': 'twitter',
				'handle': '@Colon38',
			},
			{
				'platform': 'instagram',
				'handle': '@Humphrey54',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ross Randolph',
				'phone_number': '+1 (933) 598-3662',
				'email': 'rossrandolph@pushcart.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Fannie Bass',
				'phone_number': '+1 (934) 521-3183',
				'email': 'fanniebass@pushcart.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Hannah Carey',
				'phone_number': '+1 (935) 545-3354',
				'email': 'hannahcarey@pushcart.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6ce65d97e3dc48ea0',
		'profile_picture': 'https://picsum.photos/200/300?random=509',
		'organization': 'Irorun',
		'username': 'Marilyn32',
		'fullName': 'Conner Booker',
		'email': 'connerbooker@pushcart.com',
		'date_joined': 'Dec 16, 2021 12:48 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (973) 548-2320',
		'acc_tier': 3,
		'acc_balance': 15059088,
		'acc_number': 58821842071,
		'bank_name': 'GENEKOM',
		'bvn': 2222679708,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'connerbooker@genekom.com',
		'monthly_income': {
			'min': 4035,
			'max': 10000,
		},
		'loan_repayment': 791,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Diane Price',
			},
			{
				'platform': 'twitter',
				'handle': '@Beth96',
			},
			{
				'platform': 'instagram',
				'handle': '@Sylvia66',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ochoa Kerr',
				'phone_number': '+1 (813) 537-3788',
				'email': 'ochoakerr@genekom.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Caldwell Christian',
				'phone_number': '+1 (823) 564-2722',
				'email': 'caldwellchristian@genekom.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Candy Reynolds',
				'phone_number': '+1 (917) 559-2891',
				'email': 'candyreynolds@genekom.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e69af9bc271035e765',
		'profile_picture': 'https://picsum.photos/200/300?random=555',
		'organization': 'Lendsqr',
		'username': 'Bennett33',
		'fullName': 'Gladys York',
		'email': 'gladysyork@genekom.com',
		'date_joined': 'Oct 03, 2020 07:48 AM',
		'status': 'Inactive',
		'phone_number': '+1 (970) 502-3281',
		'acc_tier': 2,
		'acc_balance': 8358,
		'acc_number': 37280728526,
		'bank_name': 'PLAYCE',
		'bvn': 2222698737,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'gladysyork@playce.com',
		'monthly_income': {
			'min': 5953,
			'max': 10000,
		},
		'loan_repayment': 604.1,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Silva Conner',
			},
			{
				'platform': 'twitter',
				'handle': '@Priscilla79',
			},
			{
				'platform': 'instagram',
				'handle': '@Mona100',
			},
		],
		'guarantor': [
			{
				'fullName': 'Shields Wagner',
				'phone_number': '+1 (817) 510-3837',
				'email': 'shieldswagner@playce.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Terrie Singleton',
				'phone_number': '+1 (999) 525-2227',
				'email': 'terriesingleton@playce.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Christie Mclean',
				'phone_number': '+1 (969) 438-2350',
				'email': 'christiemclean@playce.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e60e0e778cddd43308',
		'profile_picture': 'https://picsum.photos/200/300?random=759',
		'organization': 'Lendsqr',
		'username': 'Carr96',
		'fullName': 'Maryellen Graves',
		'email': 'maryellengraves@playce.com',
		'date_joined': 'Jul 06, 2022 02:41 AM',
		'status': 'Pending',
		'phone_number': '+1 (906) 546-2753',
		'acc_tier': 2,
		'acc_balance': 60156971,
		'acc_number': 63153749672,
		'bank_name': 'CRUSTATIA',
		'bvn': 2222682298,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'maryellengraves@crustatia.com',
		'monthly_income': {
			'min': 7018,
			'max': 10000,
		},
		'loan_repayment': 972,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Macias Wade',
			},
			{
				'platform': 'twitter',
				'handle': '@Giles82',
			},
			{
				'platform': 'instagram',
				'handle': '@Abbott72',
			},
		],
		'guarantor': [
			{
				'fullName': 'Colette Forbes',
				'phone_number': '+1 (940) 576-2691',
				'email': 'coletteforbes@crustatia.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Chang Estes',
				'phone_number': '+1 (847) 568-2625',
				'email': 'changestes@crustatia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Soto Meadows',
				'phone_number': '+1 (831) 428-2124',
				'email': 'sotomeadows@crustatia.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6f421dc7c5bb39c9b',
		'profile_picture': 'https://picsum.photos/200/300?random=235',
		'organization': 'Lendsqr',
		'username': 'Rutledge30',
		'fullName': 'Reese Santos',
		'email': 'reesesantos@crustatia.com',
		'date_joined': 'Jan 19, 2022 10:01 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (826) 523-2298',
		'acc_tier': 3,
		'acc_balance': 8442127,
		'acc_number': 16498717077,
		'bank_name': 'ACRUEX',
		'bvn': 2222657964,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'reesesantos@acruex.com',
		'monthly_income': {
			'min': 8210,
			'max': 10000,
		},
		'loan_repayment': 911.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Freda Chen',
			},
			{
				'platform': 'twitter',
				'handle': '@Ebony34',
			},
			{
				'platform': 'instagram',
				'handle': '@Fanny55',
			},
		],
		'guarantor': [
			{
				'fullName': 'Maxine Wolfe',
				'phone_number': '+1 (978) 539-3961',
				'email': 'maxinewolfe@acruex.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Stuart Bradford',
				'phone_number': '+1 (928) 411-3308',
				'email': 'stuartbradford@acruex.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Sosa Vincent',
				'phone_number': '+1 (824) 534-2795',
				'email': 'sosavincent@acruex.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '655088e6071d58b911421884',
		'profile_picture': 'https://picsum.photos/200/300?random=258',
		'organization': 'Lendstar',
		'username': 'Carson49',
		'fullName': 'Gilda Butler',
		'email': 'gildabutler@acruex.com',
		'date_joined': 'Jul 02, 2021 05:12 PM',
		'status': 'Pending',
		'phone_number': '+1 (997) 595-3663',
		'acc_tier': 1,
		'acc_balance': 95447463,
		'acc_number': 77454435213,
		'bank_name': 'ZILLANET',
		'bvn': 2222690149,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'gildabutler@zillanet.com',
		'monthly_income': {
			'min': 7920,
			'max': 10000,
		},
		'loan_repayment': 396.90000000000003,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Mcfadden Pratt',
			},
			{
				'platform': 'twitter',
				'handle': '@Barbara74',
			},
			{
				'platform': 'instagram',
				'handle': '@Lucia32',
			},
		],
		'guarantor': [
			{
				'fullName': 'Roxanne Solis',
				'phone_number': '+1 (829) 518-2260',
				'email': 'roxannesolis@zillanet.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Rowena Mcpherson',
				'phone_number': '+1 (890) 529-3804',
				'email': 'rowenamcpherson@zillanet.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Lakisha Stanton',
				'phone_number': '+1 (825) 572-3071',
				'email': 'lakishastanton@zillanet.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6c0a6f72c260d0dd6',
		'profile_picture': 'https://picsum.photos/200/300?random=474',
		'organization': 'Irorun',
		'username': 'Mathews70',
		'fullName': 'Merritt Young',
		'email': 'merrittyoung@zillanet.com',
		'date_joined': 'Aug 13, 2023 09:10 AM',
		'status': 'Active',
		'phone_number': '+1 (932) 466-2649',
		'acc_tier': 3,
		'acc_balance': 66481543,
		'acc_number': 16467999518,
		'bank_name': 'SENSATE',
		'bvn': 2222678297,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'merrittyoung@sensate.com',
		'monthly_income': {
			'min': 9196,
			'max': 10000,
		},
		'loan_repayment': 909,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Ursula Brown',
			},
			{
				'platform': 'twitter',
				'handle': '@Head41',
			},
			{
				'platform': 'instagram',
				'handle': '@Pate65',
			},
		],
		'guarantor': [
			{
				'fullName': 'Meadows Walter',
				'phone_number': '+1 (807) 511-3123',
				'email': 'meadowswalter@sensate.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Pitts Cross',
				'phone_number': '+1 (855) 588-2850',
				'email': 'pittscross@sensate.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Osborn Bowen',
				'phone_number': '+1 (854) 584-2600',
				'email': 'osbornbowen@sensate.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e640122f95b1066792',
		'profile_picture': 'https://picsum.photos/200/300?random=805',
		'organization': 'Lendsqr',
		'username': 'Richardson69',
		'fullName': 'Cash Hester',
		'email': 'cashhester@sensate.com',
		'date_joined': 'Oct 22, 2023 11:16 AM',
		'status': 'Pending',
		'phone_number': '+1 (849) 451-2756',
		'acc_tier': 2,
		'acc_balance': 5809877,
		'acc_number': 21921797033,
		'bank_name': 'ZOUNDS',
		'bvn': 2222687613,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'cashhester@zounds.com',
		'monthly_income': {
			'min': 7056,
			'max': 10000,
		},
		'loan_repayment': 378.3,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Craft Knapp',
			},
			{
				'platform': 'twitter',
				'handle': '@Leanne88',
			},
			{
				'platform': 'instagram',
				'handle': '@Melton43',
			},
		],
		'guarantor': [
			{
				'fullName': 'Ware Acosta',
				'phone_number': '+1 (812) 530-2611',
				'email': 'wareacosta@zounds.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Virgie Figueroa',
				'phone_number': '+1 (831) 532-2412',
				'email': 'virgiefigueroa@zounds.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Hunt Bruce',
				'phone_number': '+1 (897) 490-2634',
				'email': 'huntbruce@zounds.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6eb516662514f957d',
		'profile_picture': 'https://picsum.photos/200/300?random=659',
		'organization': 'Lendstar',
		'username': 'Brianna75',
		'fullName': 'Harper Rodriquez',
		'email': 'harperrodriquez@zounds.com',
		'date_joined': 'Nov 05, 2023 02:18 PM',
		'status': 'Pending',
		'phone_number': '+1 (803) 540-2312',
		'acc_tier': 3,
		'acc_balance': 35334954,
		'acc_number': 27043973490,
		'bank_name': 'ICOLOGY',
		'bvn': 2222664807,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'harperrodriquez@icology.com',
		'monthly_income': {
			'min': 4578,
			'max': 10000,
		},
		'loan_repayment': 381.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Frieda Wooten',
			},
			{
				'platform': 'twitter',
				'handle': '@Hopper45',
			},
			{
				'platform': 'instagram',
				'handle': '@Hope67',
			},
		],
		'guarantor': [
			{
				'fullName': 'Hallie Castaneda',
				'phone_number': '+1 (927) 500-2080',
				'email': 'halliecastaneda@icology.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Jami Blackwell',
				'phone_number': '+1 (812) 499-2555',
				'email': 'jamiblackwell@icology.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Mercer Evans',
				'phone_number': '+1 (965) 517-3023',
				'email': 'mercerevans@icology.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e60be154f8fabb4e17',
		'profile_picture': 'https://picsum.photos/200/300?random=286',
		'organization': 'Irorun',
		'username': 'Harrison63',
		'fullName': 'Frankie Tyson',
		'email': 'frankietyson@icology.com',
		'date_joined': 'Sep 21, 2021 11:21 PM',
		'status': 'Inactive',
		'phone_number': '+1 (852) 515-2902',
		'acc_tier': 2,
		'acc_balance': 51578291,
		'acc_number': 59549597514,
		'bank_name': 'ZENTIA',
		'bvn': 2222692972,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'frankietyson@zentia.com',
		'monthly_income': {
			'min': 4337,
			'max': 10000,
		},
		'loan_repayment': 428.3,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Carissa Good',
			},
			{
				'platform': 'twitter',
				'handle': '@Esmeralda73',
			},
			{
				'platform': 'instagram',
				'handle': '@Danielle64',
			},
		],
		'guarantor': [
			{
				'fullName': 'Doris Glenn',
				'phone_number': '+1 (955) 501-2022',
				'email': 'dorisglenn@zentia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Alford Brennan',
				'phone_number': '+1 (894) 425-3593',
				'email': 'alfordbrennan@zentia.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Ramsey Hatfield',
				'phone_number': '+1 (849) 449-2460',
				'email': 'ramseyhatfield@zentia.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e64191a6e66cdbffe9',
		'profile_picture': 'https://picsum.photos/200/300?random=876',
		'organization': 'Lendstar',
		'username': 'Vilma55',
		'fullName': 'Iva Frank',
		'email': 'ivafrank@zentia.com',
		'date_joined': 'Nov 26, 2022 05:27 PM',
		'status': 'Active',
		'phone_number': '+1 (833) 573-3992',
		'acc_tier': 3,
		'acc_balance': 82745611,
		'acc_number': 80696508558,
		'bank_name': 'TSUNAMIA',
		'bvn': 2222665942,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'ivafrank@tsunamia.com',
		'monthly_income': {
			'min': 6494,
			'max': 10000,
		},
		'loan_repayment': 382.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Beatrice Erickson',
			},
			{
				'platform': 'twitter',
				'handle': '@Dollie59',
			},
			{
				'platform': 'instagram',
				'handle': '@Ann86',
			},
		],
		'guarantor': [
			{
				'fullName': 'Knowles Peck',
				'phone_number': '+1 (860) 513-2577',
				'email': 'knowlespeck@tsunamia.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Haley Hahn',
				'phone_number': '+1 (807) 451-3833',
				'email': 'haleyhahn@tsunamia.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Beulah Brooks',
				'phone_number': '+1 (831) 449-2124',
				'email': 'beulahbrooks@tsunamia.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6ccf9d168242d3b98',
		'profile_picture': 'https://picsum.photos/200/300?random=216',
		'organization': 'Lendstar',
		'username': 'Isabelle92',
		'fullName': 'Judith Jensen',
		'email': 'judithjensen@tsunamia.com',
		'date_joined': 'Apr 12, 2023 09:07 PM',
		'status': 'Active',
		'phone_number': '+1 (832) 504-2558',
		'acc_tier': 3,
		'acc_balance': 80673256,
		'acc_number': 71889589005,
		'bank_name': 'TERAPRENE',
		'bvn': 2222665993,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'judithjensen@teraprene.com',
		'monthly_income': {
			'min': 3686,
			'max': 10000,
		},
		'loan_repayment': 642.2,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Antonia Langley',
			},
			{
				'platform': 'twitter',
				'handle': '@Lacy80',
			},
			{
				'platform': 'instagram',
				'handle': '@Eddie60',
			},
		],
		'guarantor': [
			{
				'fullName': 'Christy Kemp',
				'phone_number': '+1 (854) 417-3741',
				'email': 'christykemp@teraprene.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Catherine Shelton',
				'phone_number': '+1 (940) 433-2163',
				'email': 'catherineshelton@teraprene.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Odom Newton',
				'phone_number': '+1 (879) 431-2783',
				'email': 'odomnewton@teraprene.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e6f6e3a2d863710686',
		'profile_picture': 'https://picsum.photos/200/300?random=341',
		'organization': 'Irorun',
		'username': 'Sarah84',
		'fullName': 'Sonja Nicholson',
		'email': 'sonjanicholson@teraprene.com',
		'date_joined': 'Aug 05, 2022 12:10 AM',
		'status': 'Inactive',
		'phone_number': '+1 (858) 412-2066',
		'acc_tier': 1,
		'acc_balance': 48162356,
		'acc_number': 73588328563,
		'bank_name': 'KONNECT',
		'bvn': 2222673693,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'sonjanicholson@konnect.com',
		'monthly_income': {
			'min': 8774,
			'max': 10000,
		},
		'loan_repayment': 583.3000000000001,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Beasley Maldonado',
			},
			{
				'platform': 'twitter',
				'handle': '@Cathy79',
			},
			{
				'platform': 'instagram',
				'handle': '@Darcy89',
			},
		],
		'guarantor': [
			{
				'fullName': 'Felicia Dale',
				'phone_number': '+1 (995) 457-3044',
				'email': 'feliciadale@konnect.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'French Dennis',
				'phone_number': '+1 (829) 565-3521',
				'email': 'frenchdennis@konnect.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Strong Sims',
				'phone_number': '+1 (952) 578-3351',
				'email': 'strongsims@konnect.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e692f28e8b6007aa62',
		'profile_picture': 'https://picsum.photos/200/300?random=139',
		'organization': 'Lendsqr',
		'username': 'Navarro41',
		'fullName': 'Dianna White',
		'email': 'diannawhite@konnect.com',
		'date_joined': 'Nov 08, 2022 05:41 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (837) 436-3258',
		'acc_tier': 3,
		'acc_balance': 73925958,
		'acc_number': 72259408671,
		'bank_name': 'MIXERS',
		'bvn': 2222683250,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'diannawhite@mixers.com',
		'monthly_income': {
			'min': 7756,
			'max': 10000,
		},
		'loan_repayment': 683.6,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Casey Mathews',
			},
			{
				'platform': 'twitter',
				'handle': '@Hester46',
			},
			{
				'platform': 'instagram',
				'handle': '@Concetta62',
			},
		],
		'guarantor': [
			{
				'fullName': 'Sloan Hodge',
				'phone_number': '+1 (842) 500-2953',
				'email': 'sloanhodge@mixers.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Jordan Schultz',
				'phone_number': '+1 (978) 459-3608',
				'email': 'jordanschultz@mixers.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Cherry Ellison',
				'phone_number': '+1 (945) 541-2115',
				'email': 'cherryellison@mixers.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e673c65509ba6e03d4',
		'profile_picture': 'https://picsum.photos/200/300?random=484',
		'organization': 'Lendsqr',
		'username': 'Coffey32',
		'fullName': 'Lucas Mckee',
		'email': 'lucasmckee@mixers.com',
		'date_joined': 'Feb 17, 2023 04:07 AM',
		'status': 'Active',
		'phone_number': '+1 (991) 413-3138',
		'acc_tier': 2,
		'acc_balance': 84335182,
		'acc_number': 71263798483,
		'bank_name': 'BOILICON',
		'bvn': 2222678099,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '2 years',
		'office_email': 'lucasmckee@boilicon.com',
		'monthly_income': {
			'min': 9527,
			'max': 10000,
		},
		'loan_repayment': 782.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Cooke Case',
			},
			{
				'platform': 'twitter',
				'handle': '@Hooper66',
			},
			{
				'platform': 'instagram',
				'handle': '@Myrna90',
			},
		],
		'guarantor': [
			{
				'fullName': 'Workman Henry',
				'phone_number': '+1 (829) 430-2500',
				'email': 'workmanhenry@boilicon.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Floyd Vaughan',
				'phone_number': '+1 (875) 559-3568',
				'email': 'floydvaughan@boilicon.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Alvarez Herman',
				'phone_number': '+1 (851) 435-2687',
				'email': 'alvarezherman@boilicon.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '655088e6163f9e8a89510035',
		'profile_picture': 'https://picsum.photos/200/300?random=793',
		'organization': 'Lendstar',
		'username': 'Larsen59',
		'fullName': 'Gordon Dyer',
		'email': 'gordondyer@boilicon.com',
		'date_joined': 'Jan 13, 2020 06:15 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (904) 400-3051',
		'acc_tier': 2,
		'acc_balance': 1551186,
		'acc_number': 42175449836,
		'bank_name': 'ORONOKO',
		'bvn': 2222681235,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'gordondyer@oronoko.com',
		'monthly_income': {
			'min': 8190,
			'max': 10000,
		},
		'loan_repayment': 797.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Cervantes Gill',
			},
			{
				'platform': 'twitter',
				'handle': '@Bonnie70',
			},
			{
				'platform': 'instagram',
				'handle': '@Gina47',
			},
		],
		'guarantor': [
			{
				'fullName': 'Jensen Baldwin',
				'phone_number': '+1 (910) 489-3935',
				'email': 'jensenbaldwin@oronoko.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Bernard Barrera',
				'phone_number': '+1 (852) 462-2395',
				'email': 'bernardbarrera@oronoko.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Melody Ray',
				'phone_number': '+1 (961) 510-2923',
				'email': 'melodyray@oronoko.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '655088e617fe198af00e96cd',
		'profile_picture': 'https://picsum.photos/200/300?random=582',
		'organization': 'Lendstar',
		'username': 'Rosalind40',
		'fullName': 'Imelda Cooper',
		'email': 'imeldacooper@oronoko.com',
		'date_joined': 'Jun 13, 2020 06:47 PM',
		'status': 'Inactive',
		'phone_number': '+1 (901) 577-2320',
		'acc_tier': 3,
		'acc_balance': 96067632,
		'acc_number': 28915456515,
		'bank_name': 'PROSURE',
		'bvn': 2222681164,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'imeldacooper@prosure.com',
		'monthly_income': {
			'min': 4236,
			'max': 10000,
		},
		'loan_repayment': 797.5,
		'socials': [
			{
				'platform': 'facebook',
				'handle': 'Alejandra Medina',
			},
			{
				'platform': 'twitter',
				'handle': '@Rasmussen45',
			},
			{
				'platform': 'instagram',
				'handle': '@Adrian33',
			},
		],
		'guarantor': [
			{
				'fullName': 'Elinor Duncan',
				'phone_number': '+1 (896) 440-2062',
				'email': 'elinorduncan@prosure.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Tonya Simpson',
				'phone_number': '+1 (970) 562-2049',
				'email': 'tonyasimpson@prosure.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Jodi Pollard',
				'phone_number': '+1 (938) 441-3739',
				'email': 'jodipollard@prosure.com',
				'relationship': 'Colleague',
			},
		],
	},
];
