import { CardProps } from '../interfaces/typings';

export const cardDetails: CardProps[] = [
	{
		id: 1,
		icon: '/assets/icons/users/users.png',
		title: 'users',
		amount: 2453,
	},
	{
		id: 2,
		icon: '/assets/icons/users/active_users.png',
		title: 'active users',
		amount: 2453,
	},
	{
		id: 3,
		icon: '/assets/icons/users/loan_users.png',
		title: 'users with loans',
		amount: 12453,
	},
	{
		id: 4,
		icon: '/assets/icons/users/savings_users.png',
		title: 'users with savings',
		amount: 102453,
	},
];
export function formatNumber(number: Number) {
	const numberString = number.toString();
	return numberString.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

export const tableHeaders = ['organization', 'username', 'email', 'phone number', 'date joined', 'status'];

export const usersData = [
	{
		'id': '654e12a4a485e43c1cc8e91d',
		'organization': 'Lendstar',
		'username': 'Griffith36',
		'email': 'griffithryan@petigems.com',
		'date_joined': 'Apr 10, 2020 01:19 AM',
		'status': 'Active',
		'phone_number': '+1 (814) 483-2905',
		'acc_tier': 2,
		'acc_balance': 40989084,
		'bank_name': 'Bank A',
		'bvn': 54825742924,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'griffithryan@petigems.com',
		'monthly_income': 6058,
		'loan_repayment': 799.8000000000001,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Gomez Duke',
				'phone_number': '+1 (963) 463-3187',
				'email': 'gomezduke@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Mae Berry',
				'phone_number': '+1 (822) 560-2740',
				'email': 'maeberry@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Marlene Daugherty',
				'phone_number': '+1 (920) 423-3553',
				'email': 'marlenedaugherty@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4146aa9a468425762',
		'organization': 'Lendsqr',
		'username': 'Hooper47',
		'email': 'hooperdaugherty@petigems.com',
		'date_joined': 'Aug 03, 2022 09:22 PM',
		'status': 'Pending',
		'phone_number': '+1 (919) 600-2888',
		'acc_tier': 1,
		'acc_balance': 38726163,
		'bank_name': 'Bank A',
		'bvn': 63264946436,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'hooperdaugherty@petigems.com',
		'monthly_income': 6063,
		'loan_repayment': 406.6,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Stephenson Hood',
				'phone_number': '+1 (847) 552-3624',
				'email': 'stephensonhood@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Roseann Foley',
				'phone_number': '+1 (857) 494-2536',
				'email': 'roseannfoley@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Pennington Heath',
				'phone_number': '+1 (868) 472-2363',
				'email': 'penningtonheath@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4b666a5aea774d24c',
		'organization': 'Lendsqr',
		'username': 'Albert40',
		'email': 'albertheath@petigems.com',
		'date_joined': 'Jul 14, 2023 10:59 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (854) 472-3523',
		'acc_tier': 1,
		'acc_balance': 32633503,
		'bank_name': 'Bank C',
		'bvn': 56692817974,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'albertheath@petigems.com',
		'monthly_income': 9834,
		'loan_repayment': 942.1,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Nancy Nguyen',
				'phone_number': '+1 (902) 403-3420',
				'email': 'nancynguyen@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Sondra Browning',
				'phone_number': '+1 (931) 404-3171',
				'email': 'sondrabrowning@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Watts Tillman',
				'phone_number': '+1 (873) 546-2541',
				'email': 'wattstillman@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4fdc5d3bb3a6a17d1',
		'organization': 'Lendstar',
		'username': 'Houston93',
		'email': 'houstontillman@petigems.com',
		'date_joined': 'Oct 24, 2023 01:16 AM',
		'status': 'Inactive',
		'phone_number': '+1 (966) 409-3628',
		'acc_tier': 3,
		'acc_balance': 38973061,
		'bank_name': 'Bank C',
		'bvn': 41098279757,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'houstontillman@petigems.com',
		'monthly_income': 7261,
		'loan_repayment': 519.7,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Dollie Kane',
				'phone_number': '+1 (816) 525-3753',
				'email': 'dolliekane@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Hays Dillard',
				'phone_number': '+1 (910) 501-2657',
				'email': 'haysdillard@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Natalia Waters',
				'phone_number': '+1 (953) 521-2999',
				'email': 'nataliawaters@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4222f5dfb3b2ab48a',
		'organization': 'Lendsqr',
		'username': 'Bryant48',
		'email': 'bryantwaters@petigems.com',
		'date_joined': 'Feb 05, 2020 03:35 AM',
		'status': 'Active',
		'phone_number': '+1 (838) 580-2489',
		'acc_tier': 1,
		'acc_balance': 38308767,
		'bank_name': 'Bank B',
		'bvn': 33252603380,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'bryantwaters@petigems.com',
		'monthly_income': 7989,
		'loan_repayment': 386.40000000000003,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Buchanan Salas',
				'phone_number': '+1 (951) 529-3775',
				'email': 'buchanansalas@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Bruce Hobbs',
				'phone_number': '+1 (990) 569-3601',
				'email': 'brucehobbs@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Boyle Kirk',
				'phone_number': '+1 (852) 529-3602',
				'email': 'boylekirk@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a44f201737468a87ed',
		'organization': 'Irorun',
		'username': 'Rosalyn46',
		'email': 'rosalynkirk@petigems.com',
		'date_joined': 'Jun 24, 2023 07:42 AM',
		'status': 'Pending',
		'phone_number': '+1 (912) 529-2312',
		'acc_tier': 2,
		'acc_balance': 65243531,
		'bank_name': 'Bank A',
		'bvn': 83704306714,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'rosalynkirk@petigems.com',
		'monthly_income': 3263,
		'loan_repayment': 704.6,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Macias Hardy',
				'phone_number': '+1 (875) 401-2542',
				'email': 'maciashardy@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Wise Cochran',
				'phone_number': '+1 (954) 537-2518',
				'email': 'wisecochran@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Loraine Bryant',
				'phone_number': '+1 (982) 523-3148',
				'email': 'lorainebryant@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4031d627ed34d406f',
		'organization': 'Lendstar',
		'username': 'Hancock47',
		'email': 'hancockbryant@petigems.com',
		'date_joined': 'Oct 30, 2020 08:51 PM',
		'status': 'Pending',
		'phone_number': '+1 (988) 461-2120',
		'acc_tier': 2,
		'acc_balance': 13159373,
		'bank_name': 'Bank A',
		'bvn': 31669012118,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'hancockbryant@petigems.com',
		'monthly_income': 3010,
		'loan_repayment': 957.7,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Ayala Ellis',
				'phone_number': '+1 (804) 516-2543',
				'email': 'ayalaellis@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Angelia Mendez',
				'phone_number': '+1 (941) 458-3818',
				'email': 'angeliamendez@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Juliet Mullen',
				'phone_number': '+1 (976) 446-3687',
				'email': 'julietmullen@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a42e0eb665f116596f',
		'organization': 'Lendstar',
		'username': 'Corrine73',
		'email': 'corrinemullen@petigems.com',
		'date_joined': 'Dec 30, 2022 05:05 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (842) 406-3175',
		'acc_tier': 1,
		'acc_balance': 23030495,
		'bank_name': 'Bank A',
		'bvn': 40466002599,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'corrinemullen@petigems.com',
		'monthly_income': 8291,
		'loan_repayment': 611.1,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Alfreda Mathews',
				'phone_number': '+1 (858) 483-2729',
				'email': 'alfredamathews@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Deann Warren',
				'phone_number': '+1 (925) 583-2764',
				'email': 'deannwarren@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Kelley Marquez',
				'phone_number': '+1 (918) 498-2440',
				'email': 'kelleymarquez@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a43dbd7c23c78e0f87',
		'organization': 'Lendsqr',
		'username': 'Luann36',
		'email': 'luannmarquez@petigems.com',
		'date_joined': 'Apr 14, 2021 04:27 PM',
		'status': 'Pending',
		'phone_number': '+1 (946) 467-3805',
		'acc_tier': 1,
		'acc_balance': 25465201,
		'bank_name': 'Bank B',
		'bvn': 15086671676,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'luannmarquez@petigems.com',
		'monthly_income': 8041,
		'loan_repayment': 911.3000000000001,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Tammi Sheppard',
				'phone_number': '+1 (900) 427-2189',
				'email': 'tammisheppard@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Jerri Arnold',
				'phone_number': '+1 (827) 577-3425',
				'email': 'jerriarnold@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Ophelia Francis',
				'phone_number': '+1 (985) 554-3273',
				'email': 'opheliafrancis@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a43f36159ba0a90619',
		'organization': 'Irorun',
		'username': 'Whitney66',
		'email': 'whitneyfrancis@petigems.com',
		'date_joined': 'Jul 07, 2021 07:53 PM',
		'status': 'Active',
		'phone_number': '+1 (862) 587-2880',
		'acc_tier': 2,
		'acc_balance': 5884003,
		'bank_name': 'Bank A',
		'bvn': 28044565690,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'whitneyfrancis@petigems.com',
		'monthly_income': 5520,
		'loan_repayment': 858.6,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Elba Juarez',
				'phone_number': '+1 (864) 600-2728',
				'email': 'elbajuarez@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Hayes Baxter',
				'phone_number': '+1 (942) 509-2762',
				'email': 'hayesbaxter@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Ebony Roman',
				'phone_number': '+1 (848) 401-2716',
				'email': 'ebonyroman@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a486956f8ff07a6e9d',
		'organization': 'Lendstar',
		'username': 'Concepcion33',
		'email': 'concepcionroman@petigems.com',
		'date_joined': 'Sep 23, 2020 01:44 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (871) 590-3352',
		'acc_tier': 2,
		'acc_balance': 69503386,
		'bank_name': 'Bank B',
		'bvn': 43409248091,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'concepcionroman@petigems.com',
		'monthly_income': 6163,
		'loan_repayment': 579.9,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Strong Gillespie',
				'phone_number': '+1 (873) 447-2810',
				'email': 'stronggillespie@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Kelley Pacheco',
				'phone_number': '+1 (903) 553-2651',
				'email': 'kelleypacheco@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Flossie Wooten',
				'phone_number': '+1 (949) 561-2323',
				'email': 'flossiewooten@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a465e075f56b93dfc9',
		'organization': 'Irorun',
		'username': 'Hobbs41',
		'email': 'hobbswooten@petigems.com',
		'date_joined': 'Nov 11, 2020 10:33 AM',
		'status': 'Active',
		'phone_number': '+1 (870) 426-3362',
		'acc_tier': 2,
		'acc_balance': 25485951,
		'bank_name': 'Bank B',
		'bvn': 94819926552,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'hobbswooten@petigems.com',
		'monthly_income': 3084,
		'loan_repayment': 430,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Burks Valencia',
				'phone_number': '+1 (912) 573-2806',
				'email': 'burksvalencia@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Nona Boyd',
				'phone_number': '+1 (923) 491-2646',
				'email': 'nonaboyd@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Mavis Bentley',
				'phone_number': '+1 (986) 564-2252',
				'email': 'mavisbentley@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4378be7e9351a7eca',
		'organization': 'Lendstar',
		'username': 'Mollie47',
		'email': 'molliebentley@petigems.com',
		'date_joined': 'Apr 05, 2020 12:24 PM',
		'status': 'Active',
		'phone_number': '+1 (987) 428-2622',
		'acc_tier': 2,
		'acc_balance': 4334608,
		'bank_name': 'Bank C',
		'bvn': 79868953368,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'molliebentley@petigems.com',
		'monthly_income': 5263,
		'loan_repayment': 886.6,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Moses Santiago',
				'phone_number': '+1 (819) 479-3064',
				'email': 'mosessantiago@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Washington Ross',
				'phone_number': '+1 (926) 488-2260',
				'email': 'washingtonross@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Roberta Irwin',
				'phone_number': '+1 (949) 578-2257',
				'email': 'robertairwin@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4f55abdb04f36adc9',
		'organization': 'Irorun',
		'username': 'Kathleen70',
		'email': 'kathleenirwin@petigems.com',
		'date_joined': 'Aug 28, 2023 02:39 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (994) 532-2005',
		'acc_tier': 1,
		'acc_balance': 61624129,
		'bank_name': 'Bank B',
		'bvn': 14629001400,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'kathleenirwin@petigems.com',
		'monthly_income': 4685,
		'loan_repayment': 939.7,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Wood Holmes',
				'phone_number': '+1 (939) 441-2823',
				'email': 'woodholmes@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Gonzalez Conrad',
				'phone_number': '+1 (935) 574-3185',
				'email': 'gonzalezconrad@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Lilly Dalton',
				'phone_number': '+1 (919) 442-3831',
				'email': 'lillydalton@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4f24bc8ced07aaa0e',
		'organization': 'Irorun',
		'username': 'Ortiz38',
		'email': 'ortizdalton@petigems.com',
		'date_joined': 'Mar 25, 2023 05:28 PM',
		'status': 'Active',
		'phone_number': '+1 (885) 520-2351',
		'acc_tier': 1,
		'acc_balance': 21064655,
		'bank_name': 'Bank C',
		'bvn': 60255405373,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'ortizdalton@petigems.com',
		'monthly_income': 8389,
		'loan_repayment': 470.6,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Kate Peterson',
				'phone_number': '+1 (892) 437-2254',
				'email': 'katepeterson@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Hampton Hogan',
				'phone_number': '+1 (985) 480-3016',
				'email': 'hamptonhogan@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Florine Weaver',
				'phone_number': '+1 (947) 553-2022',
				'email': 'florineweaver@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a492b636cf0e433145',
		'organization': 'Lendsqr',
		'username': 'Hull54',
		'email': 'hullweaver@petigems.com',
		'date_joined': 'Jul 02, 2022 06:37 AM',
		'status': 'Inactive',
		'phone_number': '+1 (977) 445-2513',
		'acc_tier': 2,
		'acc_balance': 83910511,
		'bank_name': 'Bank B',
		'bvn': 97757667269,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'hullweaver@petigems.com',
		'monthly_income': 6590,
		'loan_repayment': 302.2,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Angela Dean',
				'phone_number': '+1 (845) 465-3719',
				'email': 'angeladean@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Catherine Duffy',
				'phone_number': '+1 (819) 433-3164',
				'email': 'catherineduffy@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Alexis Kramer',
				'phone_number': '+1 (968) 569-3488',
				'email': 'alexiskramer@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4f0290dfa290edf03',
		'organization': 'Irorun',
		'username': 'Georgina46',
		'email': 'georginakramer@petigems.com',
		'date_joined': 'Jul 16, 2020 05:11 PM',
		'status': 'Active',
		'phone_number': '+1 (964) 582-2680',
		'acc_tier': 2,
		'acc_balance': 20017015,
		'bank_name': 'Bank B',
		'bvn': 37887046681,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'georginakramer@petigems.com',
		'monthly_income': 7953,
		'loan_repayment': 860.1,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Bishop Parks',
				'phone_number': '+1 (968) 491-2594',
				'email': 'bishopparks@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Lucile Carney',
				'phone_number': '+1 (936) 567-2443',
				'email': 'lucilecarney@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Sadie Travis',
				'phone_number': '+1 (860) 462-2045',
				'email': 'sadietravis@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4eb9e331c78c96d44',
		'organization': 'Lendsqr',
		'username': 'Karyn71',
		'email': 'karyntravis@petigems.com',
		'date_joined': 'Nov 15, 2022 11:40 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (949) 564-2466',
		'acc_tier': 2,
		'acc_balance': 99099533,
		'bank_name': 'Bank A',
		'bvn': 13682273546,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'karyntravis@petigems.com',
		'monthly_income': 8101,
		'loan_repayment': 939.4000000000001,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Barker Morton',
				'phone_number': '+1 (909) 585-3518',
				'email': 'barkermorton@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Owen Ward',
				'phone_number': '+1 (915) 542-2666',
				'email': 'owenward@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Park Keller',
				'phone_number': '+1 (932) 479-2671',
				'email': 'parkkeller@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a45c7af18f27edb052',
		'organization': 'Irorun',
		'username': 'Peters54',
		'email': 'peterskeller@petigems.com',
		'date_joined': 'Oct 25, 2021 08:24 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (834) 552-2714',
		'acc_tier': 2,
		'acc_balance': 10814092,
		'bank_name': 'Bank B',
		'bvn': 85806626858,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'peterskeller@petigems.com',
		'monthly_income': 7973,
		'loan_repayment': 731,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Haney Mckee',
				'phone_number': '+1 (952) 455-2172',
				'email': 'haneymckee@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Debra Bates',
				'phone_number': '+1 (924) 446-2994',
				'email': 'debrabates@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Willie Perkins',
				'phone_number': '+1 (938) 403-2195',
				'email': 'willieperkins@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a48cf2005adaeac65a',
		'organization': 'Lendsqr',
		'username': 'Patricia92',
		'email': 'patriciaperkins@petigems.com',
		'date_joined': 'Jun 20, 2023 07:23 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (948) 530-2164',
		'acc_tier': 2,
		'acc_balance': 5393869,
		'bank_name': 'Bank B',
		'bvn': 74533399742,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '2 years',
		'office_email': 'patriciaperkins@petigems.com',
		'monthly_income': 9939,
		'loan_repayment': 820.9000000000001,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Reyna Odonnell',
				'phone_number': '+1 (933) 447-3512',
				'email': 'reynaodonnell@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Arlene Montoya',
				'phone_number': '+1 (807) 455-3582',
				'email': 'arlenemontoya@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Olivia Martinez',
				'phone_number': '+1 (842) 514-3762',
				'email': 'oliviamartinez@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a49ba128d4cc1002b2',
		'organization': 'Irorun',
		'username': 'Etta79',
		'email': 'ettamartinez@petigems.com',
		'date_joined': 'Feb 17, 2021 12:04 AM',
		'status': 'Active',
		'phone_number': '+1 (963) 410-3464',
		'acc_tier': 2,
		'acc_balance': 24097051,
		'bank_name': 'Bank B',
		'bvn': 50989066559,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'ettamartinez@petigems.com',
		'monthly_income': 9722,
		'loan_repayment': 688.6,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Douglas Stein',
				'phone_number': '+1 (888) 559-3003',
				'email': 'douglasstein@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Deirdre Caldwell',
				'phone_number': '+1 (881) 517-2129',
				'email': 'deirdrecaldwell@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Preston Suarez',
				'phone_number': '+1 (830) 537-2138',
				'email': 'prestonsuarez@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4c0d22d856797f4ab',
		'organization': 'Lendstar',
		'username': 'Ball75',
		'email': 'ballsuarez@petigems.com',
		'date_joined': 'Apr 12, 2021 01:25 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (859) 449-2256',
		'acc_tier': 2,
		'acc_balance': 37650558,
		'bank_name': 'Bank A',
		'bvn': 70872957211,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'ballsuarez@petigems.com',
		'monthly_income': 4405,
		'loan_repayment': 858.3000000000001,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Winifred Dickson',
				'phone_number': '+1 (823) 565-3133',
				'email': 'winifreddickson@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Rich Owens',
				'phone_number': '+1 (918) 501-3058',
				'email': 'richowens@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Wilma Green',
				'phone_number': '+1 (922) 543-2448',
				'email': 'wilmagreen@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a477a2cdda2b8a6e63',
		'organization': 'Irorun',
		'username': 'Carmela48',
		'email': 'carmelagreen@petigems.com',
		'date_joined': 'May 23, 2020 05:54 PM',
		'status': 'Inactive',
		'phone_number': '+1 (811) 408-3390',
		'acc_tier': 1,
		'acc_balance': 360078,
		'bank_name': 'Bank A',
		'bvn': 90255651726,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'carmelagreen@petigems.com',
		'monthly_income': 3550,
		'loan_repayment': 726.9000000000001,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Mable Lowe',
				'phone_number': '+1 (871) 520-2320',
				'email': 'mablelowe@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Navarro Goff',
				'phone_number': '+1 (965) 593-2159',
				'email': 'navarrogoff@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Singleton Watkins',
				'phone_number': '+1 (994) 416-2615',
				'email': 'singletonwatkins@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4d15842d87abc528a',
		'organization': 'Lendsqr',
		'username': 'Jeannette90',
		'email': 'jeannettewatkins@petigems.com',
		'date_joined': 'Jun 16, 2021 12:25 AM',
		'status': 'Inactive',
		'phone_number': '+1 (849) 406-3670',
		'acc_tier': 1,
		'acc_balance': 7817303,
		'bank_name': 'Bank B',
		'bvn': 11254785563,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'jeannettewatkins@petigems.com',
		'monthly_income': 7072,
		'loan_repayment': 346.8,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Shana Nielsen',
				'phone_number': '+1 (897) 520-3013',
				'email': 'shananielsen@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Kaye Underwood',
				'phone_number': '+1 (960) 412-2196',
				'email': 'kayeunderwood@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Doris Cunningham',
				'phone_number': '+1 (986) 412-2223',
				'email': 'doriscunningham@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4f99ffc77a0cddd79',
		'organization': 'Lendsqr',
		'username': 'Mamie98',
		'email': 'mamiecunningham@petigems.com',
		'date_joined': 'Aug 30, 2022 03:36 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (858) 572-2204',
		'acc_tier': 1,
		'acc_balance': 24312057,
		'bank_name': 'Bank A',
		'bvn': 92857856637,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'mamiecunningham@petigems.com',
		'monthly_income': 8008,
		'loan_repayment': 317.3,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Bertha Preston',
				'phone_number': '+1 (932) 559-3221',
				'email': 'berthapreston@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Kathie Benton',
				'phone_number': '+1 (806) 560-3547',
				'email': 'kathiebenton@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Wolf Ferrell',
				'phone_number': '+1 (943) 469-2195',
				'email': 'wolfferrell@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4d916f86594a74dec',
		'organization': 'Irorun',
		'username': 'Daugherty76',
		'email': 'daughertyferrell@petigems.com',
		'date_joined': 'Apr 25, 2021 02:23 PM',
		'status': 'Pending',
		'phone_number': '+1 (945) 585-3552',
		'acc_tier': 2,
		'acc_balance': 84968288,
		'bank_name': 'Bank B',
		'bvn': 19946797910,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'daughertyferrell@petigems.com',
		'monthly_income': 9530,
		'loan_repayment': 521.4,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Mcneil Crane',
				'phone_number': '+1 (851) 568-2075',
				'email': 'mcneilcrane@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Audrey Stokes',
				'phone_number': '+1 (838) 513-2261',
				'email': 'audreystokes@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Coleman Ferguson',
				'phone_number': '+1 (837) 519-2081',
				'email': 'colemanferguson@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4d80969bbc028831b',
		'organization': 'Lendsqr',
		'username': 'Cotton80',
		'email': 'cottonferguson@petigems.com',
		'date_joined': 'Aug 02, 2023 08:37 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (814) 564-3405',
		'acc_tier': 2,
		'acc_balance': 64712790,
		'bank_name': 'Bank A',
		'bvn': 81402714306,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'cottonferguson@petigems.com',
		'monthly_income': 6416,
		'loan_repayment': 475,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Marsha Pope',
				'phone_number': '+1 (984) 493-2828',
				'email': 'marshapope@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Velma Lambert',
				'phone_number': '+1 (904) 502-2394',
				'email': 'velmalambert@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'James Saunders',
				'phone_number': '+1 (930) 401-3089',
				'email': 'jamessaunders@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a449a8a5f7c119add0',
		'organization': 'Irorun',
		'username': 'Lindsey50',
		'email': 'lindseysaunders@petigems.com',
		'date_joined': 'Feb 26, 2023 01:29 AM',
		'status': 'Inactive',
		'phone_number': '+1 (851) 405-3957',
		'acc_tier': 3,
		'acc_balance': 33082843,
		'bank_name': 'Bank C',
		'bvn': 12710389703,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'lindseysaunders@petigems.com',
		'monthly_income': 6292,
		'loan_repayment': 810.9000000000001,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Martina Puckett',
				'phone_number': '+1 (967) 485-3443',
				'email': 'martinapuckett@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Tamara Gonzalez',
				'phone_number': '+1 (865) 506-2052',
				'email': 'tamaragonzalez@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Stephens Petersen',
				'phone_number': '+1 (968) 545-3185',
				'email': 'stephenspetersen@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a447746b5fabc0ddd5',
		'organization': 'Lendstar',
		'username': 'Tammie64',
		'email': 'tammiepetersen@petigems.com',
		'date_joined': 'Feb 23, 2022 03:57 AM',
		'status': 'Active',
		'phone_number': '+1 (874) 446-2650',
		'acc_tier': 3,
		'acc_balance': 69223167,
		'bank_name': 'Bank C',
		'bvn': 71182279435,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'tammiepetersen@petigems.com',
		'monthly_income': 9828,
		'loan_repayment': 525.8000000000001,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Burton Knapp',
				'phone_number': '+1 (948) 546-2426',
				'email': 'burtonknapp@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lou Davidson',
				'phone_number': '+1 (935) 517-3505',
				'email': 'loudavidson@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Pat Nelson',
				'phone_number': '+1 (922) 441-3713',
				'email': 'patnelson@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a40972c1abed7da9db',
		'organization': 'Irorun',
		'username': 'Graciela54',
		'email': 'gracielanelson@petigems.com',
		'date_joined': 'Feb 15, 2022 04:22 PM',
		'status': 'Inactive',
		'phone_number': '+1 (987) 492-2171',
		'acc_tier': 1,
		'acc_balance': 57480046,
		'bank_name': 'Bank B',
		'bvn': 89894572402,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'gracielanelson@petigems.com',
		'monthly_income': 3788,
		'loan_repayment': 374.6,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Drake Pittman',
				'phone_number': '+1 (923) 562-3630',
				'email': 'drakepittman@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Kinney Chaney',
				'phone_number': '+1 (911) 504-2564',
				'email': 'kinneychaney@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Lisa Shelton',
				'phone_number': '+1 (844) 519-2701',
				'email': 'lisashelton@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a48e4ad022ad49e68d',
		'organization': 'Lendsqr',
		'username': 'Taylor92',
		'email': 'taylorshelton@petigems.com',
		'date_joined': 'Dec 06, 2022 09:16 AM',
		'status': 'Active',
		'phone_number': '+1 (891) 557-2689',
		'acc_tier': 1,
		'acc_balance': 19337670,
		'bank_name': 'Bank C',
		'bvn': 80649785602,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'taylorshelton@petigems.com',
		'monthly_income': 9442,
		'loan_repayment': 960,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Carr Callahan',
				'phone_number': '+1 (974) 482-3811',
				'email': 'carrcallahan@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Dorothea Sullivan',
				'phone_number': '+1 (806) 529-3861',
				'email': 'dorotheasullivan@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Cruz Bright',
				'phone_number': '+1 (808) 471-2563',
				'email': 'cruzbright@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a40941c2da05e99dfb',
		'organization': 'Lendsqr',
		'username': 'Maxine95',
		'email': 'maxinebright@petigems.com',
		'date_joined': 'Feb 17, 2022 03:52 PM',
		'status': 'Active',
		'phone_number': '+1 (879) 568-2908',
		'acc_tier': 2,
		'acc_balance': 1831364,
		'bank_name': 'Bank B',
		'bvn': 97809228978,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'maxinebright@petigems.com',
		'monthly_income': 3572,
		'loan_repayment': 480.70000000000005,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Parker Pratt',
				'phone_number': '+1 (919) 574-2793',
				'email': 'parkerpratt@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Gabriela Berger',
				'phone_number': '+1 (808) 501-3631',
				'email': 'gabrielaberger@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Lynne Snyder',
				'phone_number': '+1 (870) 593-3244',
				'email': 'lynnesnyder@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a44411622c3b2db178',
		'organization': 'Lendstar',
		'username': 'Alvarez32',
		'email': 'alvarezsnyder@petigems.com',
		'date_joined': 'Sep 12, 2021 12:01 PM',
		'status': 'Inactive',
		'phone_number': '+1 (947) 407-3052',
		'acc_tier': 3,
		'acc_balance': 6128052,
		'bank_name': 'Bank C',
		'bvn': 77221580696,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'alvarezsnyder@petigems.com',
		'monthly_income': 3766,
		'loan_repayment': 375.8,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Victoria Gaines',
				'phone_number': '+1 (868) 450-3120',
				'email': 'victoriagaines@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Clarissa Mays',
				'phone_number': '+1 (910) 445-3535',
				'email': 'clarissamays@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Raquel Whitehead',
				'phone_number': '+1 (917) 569-3218',
				'email': 'raquelwhitehead@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4cb88d1703c4b5093',
		'organization': 'Lendstar',
		'username': 'Susan56',
		'email': 'susanwhitehead@petigems.com',
		'date_joined': 'Jun 18, 2022 04:05 AM',
		'status': 'Active',
		'phone_number': '+1 (930) 473-3553',
		'acc_tier': 1,
		'acc_balance': 21653996,
		'bank_name': 'Bank A',
		'bvn': 47625410469,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'susanwhitehead@petigems.com',
		'monthly_income': 5087,
		'loan_repayment': 807.6,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Massey Taylor',
				'phone_number': '+1 (921) 457-3785',
				'email': 'masseytaylor@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Colon Phillips',
				'phone_number': '+1 (965) 417-3962',
				'email': 'colonphillips@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Boyer Mcmillan',
				'phone_number': '+1 (857) 413-2497',
				'email': 'boyermcmillan@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a45d7b6645df3767f9',
		'organization': 'Irorun',
		'username': 'Maura45',
		'email': 'mauramcmillan@petigems.com',
		'date_joined': 'Jun 06, 2021 05:51 AM',
		'status': 'Pending',
		'phone_number': '+1 (806) 560-3141',
		'acc_tier': 1,
		'acc_balance': 70413998,
		'bank_name': 'Bank C',
		'bvn': 83639474797,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'mauramcmillan@petigems.com',
		'monthly_income': 7475,
		'loan_repayment': 546.5,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Odessa Dudley',
				'phone_number': '+1 (964) 436-3467',
				'email': 'odessadudley@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Craft Spence',
				'phone_number': '+1 (823) 543-3388',
				'email': 'craftspence@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Margo Rasmussen',
				'phone_number': '+1 (948) 463-2768',
				'email': 'margorasmussen@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4652cdd7e8ef8877f',
		'organization': 'Lendstar',
		'username': 'Manuela50',
		'email': 'manuelarasmussen@petigems.com',
		'date_joined': 'May 10, 2022 08:31 AM',
		'status': 'Active',
		'phone_number': '+1 (865) 497-3465',
		'acc_tier': 2,
		'acc_balance': 16329589,
		'bank_name': 'Bank A',
		'bvn': 41655111707,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'manuelarasmussen@petigems.com',
		'monthly_income': 3999,
		'loan_repayment': 478.8,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Eve Chan',
				'phone_number': '+1 (947) 498-2495',
				'email': 'evechan@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Good Christensen',
				'phone_number': '+1 (818) 516-3153',
				'email': 'goodchristensen@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Norton Ashley',
				'phone_number': '+1 (864) 483-3923',
				'email': 'nortonashley@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4ffb26be1ffb0e98b',
		'organization': 'Lendstar',
		'username': 'Harding34',
		'email': 'hardingashley@petigems.com',
		'date_joined': 'Mar 17, 2022 12:20 AM',
		'status': 'Pending',
		'phone_number': '+1 (932) 502-2235',
		'acc_tier': 3,
		'acc_balance': 61431795,
		'bank_name': 'Bank B',
		'bvn': 72328869666,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'hardingashley@petigems.com',
		'monthly_income': 6376,
		'loan_repayment': 659.8000000000001,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Maddox Cross',
				'phone_number': '+1 (864) 429-2758',
				'email': 'maddoxcross@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Joni Hoover',
				'phone_number': '+1 (915) 535-2638',
				'email': 'jonihoover@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Rene Oneil',
				'phone_number': '+1 (860) 496-2856',
				'email': 'reneoneil@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a46da57920e4cd6ee2',
		'organization': 'Irorun',
		'username': 'Bray78',
		'email': 'brayoneil@petigems.com',
		'date_joined': 'May 20, 2022 08:31 AM',
		'status': 'Pending',
		'phone_number': '+1 (811) 538-2459',
		'acc_tier': 1,
		'acc_balance': 32291678,
		'bank_name': 'Bank B',
		'bvn': 14695709691,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'brayoneil@petigems.com',
		'monthly_income': 4477,
		'loan_repayment': 931.2,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Jolene Reese',
				'phone_number': '+1 (942) 583-3155',
				'email': 'jolenereese@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Blankenship Gardner',
				'phone_number': '+1 (829) 506-2940',
				'email': 'blankenshipgardner@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Macdonald Ford',
				'phone_number': '+1 (889) 550-3761',
				'email': 'macdonaldford@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4e3433cc30336684a',
		'organization': 'Lendstar',
		'username': 'Giles34',
		'email': 'gilesford@petigems.com',
		'date_joined': 'Jan 14, 2020 09:15 AM',
		'status': 'Active',
		'phone_number': '+1 (959) 547-3368',
		'acc_tier': 2,
		'acc_balance': 59158583,
		'bank_name': 'Bank B',
		'bvn': 49307833211,
		'gender': 'Female',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '3 years',
		'office_email': 'gilesford@petigems.com',
		'monthly_income': 5108,
		'loan_repayment': 420.8,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Latoya Solomon',
				'phone_number': '+1 (933) 429-2802',
				'email': 'latoyasolomon@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Alexander Lester',
				'phone_number': '+1 (994) 587-3921',
				'email': 'alexanderlester@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Norris Deleon',
				'phone_number': '+1 (824) 453-2124',
				'email': 'norrisdeleon@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4ce254ad626830a16',
		'organization': 'Irorun',
		'username': 'Janis36',
		'email': 'janisdeleon@petigems.com',
		'date_joined': 'Sep 08, 2021 11:16 PM',
		'status': 'Active',
		'phone_number': '+1 (818) 562-2636',
		'acc_tier': 2,
		'acc_balance': 97203885,
		'bank_name': 'Bank A',
		'bvn': 88247911987,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Own Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '2 years',
		'office_email': 'janisdeleon@petigems.com',
		'monthly_income': 3089,
		'loan_repayment': 726.2,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Bird Farley',
				'phone_number': '+1 (891) 544-3127',
				'email': 'birdfarley@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Dena Bush',
				'phone_number': '+1 (926) 422-2874',
				'email': 'denabush@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'April Murray',
				'phone_number': '+1 (864) 515-2046',
				'email': 'aprilmurray@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a44e955123c3b2adcb',
		'organization': 'Irorun',
		'username': 'Ana76',
		'email': 'anamurray@petigems.com',
		'date_joined': 'Apr 08, 2022 06:52 PM',
		'status': 'Blacklisted',
		'phone_number': '+1 (861) 454-3991',
		'acc_tier': 2,
		'acc_balance': 20730630,
		'bank_name': 'Bank B',
		'bvn': 27480464428,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'anamurray@petigems.com',
		'monthly_income': 7591,
		'loan_repayment': 870.7,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Sparks Wilder',
				'phone_number': '+1 (939) 590-3032',
				'email': 'sparkswilder@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Rosella Trujillo',
				'phone_number': '+1 (858) 554-2390',
				'email': 'rosellatrujillo@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Robyn Berg',
				'phone_number': '+1 (858) 595-2888',
				'email': 'robynberg@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a43f37339c45030f85',
		'organization': 'Lendsqr',
		'username': 'Cummings98',
		'email': 'cummingsberg@petigems.com',
		'date_joined': 'Jun 13, 2020 11:43 AM',
		'status': 'Pending',
		'phone_number': '+1 (854) 478-3002',
		'acc_tier': 1,
		'acc_balance': 31893785,
		'bank_name': 'Bank A',
		'bvn': 13730463490,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Bachelor's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'cummingsberg@petigems.com',
		'monthly_income': 5905,
		'loan_repayment': 992,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Aileen Dorsey',
				'phone_number': '+1 (827) 431-2500',
				'email': 'aileendorsey@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Dillon English',
				'phone_number': '+1 (916) 495-3860',
				'email': 'dillonenglish@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Phyllis Vincent',
				'phone_number': '+1 (962) 534-2035',
				'email': 'phyllisvincent@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4dce7e5b66fb33f28',
		'organization': 'Irorun',
		'username': 'Rivas53',
		'email': 'rivasvincent@petigems.com',
		'date_joined': 'Feb 01, 2020 09:27 AM',
		'status': 'Pending',
		'phone_number': '+1 (823) 503-3354',
		'acc_tier': 1,
		'acc_balance': 91756717,
		'bank_name': 'Bank B',
		'bvn': 97863809342,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Employed',
		'industry': 'Healthcare',
		'duration_of_employment': '1 year',
		'office_email': 'rivasvincent@petigems.com',
		'monthly_income': 9119,
		'loan_repayment': 863.6,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Tommie Barlow',
				'phone_number': '+1 (948) 463-2751',
				'email': 'tommiebarlow@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Huber Waller',
				'phone_number': '+1 (867) 459-3396',
				'email': 'huberwaller@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Frye Norman',
				'phone_number': '+1 (872) 411-3005',
				'email': 'fryenorman@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4b4a667af54c8847e',
		'organization': 'Lendstar',
		'username': 'Harriet34',
		'email': 'harrietnorman@petigems.com',
		'date_joined': 'Oct 18, 2021 04:08 PM',
		'status': 'Inactive',
		'phone_number': '+1 (983) 468-3079',
		'acc_tier': 2,
		'acc_balance': 51454919,
		'bank_name': 'Bank C',
		'bvn': 72542665138,
		'gender': 'Female',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '1 year',
		'office_email': 'harrietnorman@petigems.com',
		'monthly_income': 3058,
		'loan_repayment': 599.2,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Barton Frye',
				'phone_number': '+1 (839) 454-3920',
				'email': 'bartonfrye@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Richard Shannon',
				'phone_number': '+1 (912) 551-3151',
				'email': 'richardshannon@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Morrow Palmer',
				'phone_number': '+1 (887) 539-2172',
				'email': 'morrowpalmer@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a40cfa851f24486e76',
		'organization': 'Lendstar',
		'username': 'Elisa100',
		'email': 'elisapalmer@petigems.com',
		'date_joined': 'May 11, 2023 07:38 PM',
		'status': 'Inactive',
		'phone_number': '+1 (904) 455-3920',
		'acc_tier': 3,
		'acc_balance': 21079380,
		'bank_name': 'Bank C',
		'bvn': 61914277808,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'elisapalmer@petigems.com',
		'monthly_income': 4399,
		'loan_repayment': 953.6,
		'socials': ['linkedin'],
		'guarantor': [
			{
				'fullName': 'Harris Fisher',
				'phone_number': '+1 (918) 489-2292',
				'email': 'harrisfisher@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Osborn Stephens',
				'phone_number': '+1 (857) 486-2747',
				'email': 'osbornstephens@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Vickie Bond',
				'phone_number': '+1 (855) 467-2873',
				'email': 'vickiebond@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a4045cdeec1b2b5405',
		'organization': 'Irorun',
		'username': 'Alvarado63',
		'email': 'alvaradobond@petigems.com',
		'date_joined': 'Jul 28, 2022 04:32 AM',
		'status': 'Active',
		'phone_number': '+1 (977) 571-3517',
		'acc_tier': 2,
		'acc_balance': 73389627,
		'bank_name': 'Bank A',
		'bvn': 94183227049,
		'gender': 'Male',
		'marital_status': 'Married',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '1 year',
		'office_email': 'alvaradobond@petigems.com',
		'monthly_income': 5378,
		'loan_repayment': 331.90000000000003,
		'socials': ['twitter'],
		'guarantor': [
			{
				'fullName': 'Cardenas Stanley',
				'phone_number': '+1 (820) 465-3052',
				'email': 'cardenasstanley@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Annette Rosales',
				'phone_number': '+1 (883) 429-3796',
				'email': 'annetterosales@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Love Fulton',
				'phone_number': '+1 (841) 442-2938',
				'email': 'lovefulton@petigems.com',
				'relationship': 'Family',
			},
		],
	},
	{
		'id': '654e12a44c91a756fa8f462d',
		'organization': 'Lendstar',
		'username': 'Clark87',
		'email': 'clarkfulton@petigems.com',
		'date_joined': 'Feb 02, 2023 01:02 PM',
		'status': 'Inactive',
		'phone_number': '+1 (907) 512-3435',
		'acc_tier': 3,
		'acc_balance': 44044592,
		'bank_name': 'Bank C',
		'bvn': 46781998167,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'Yes',
		'resident_type': 'Own Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Employed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'clarkfulton@petigems.com',
		'monthly_income': 6262,
		'loan_repayment': 326.1,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Mandy Schultz',
				'phone_number': '+1 (949) 475-3040',
				'email': 'mandyschultz@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Alston Vargas',
				'phone_number': '+1 (964) 496-2520',
				'email': 'alstonvargas@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Gina Blevins',
				'phone_number': '+1 (977) 403-3852',
				'email': 'ginablevins@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a4e1e651222dfff920',
		'organization': 'Irorun',
		'username': 'Snider46',
		'email': 'sniderblevins@petigems.com',
		'date_joined': 'Mar 31, 2021 11:32 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (933) 522-3094',
		'acc_tier': 3,
		'acc_balance': 34200049,
		'bank_name': 'Bank A',
		'bvn': 82751011546,
		'gender': 'Male',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'sniderblevins@petigems.com',
		'monthly_income': 9123,
		'loan_repayment': 998.4000000000001,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Frederick Brady',
				'phone_number': '+1 (950) 467-3534',
				'email': 'frederickbrady@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Maynard Evans',
				'phone_number': '+1 (824) 524-2093',
				'email': 'maynardevans@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Aline Mooney',
				'phone_number': '+1 (812) 407-2012',
				'email': 'alinemooney@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
	{
		'id': '654e12a48ddc8e7831e31fae',
		'organization': 'Lendsqr',
		'username': 'Dunn57',
		'email': 'dunnmooney@petigems.com',
		'date_joined': 'Jun 27, 2022 10:29 AM',
		'status': 'Blacklisted',
		'phone_number': '+1 (883) 519-2424',
		'acc_tier': 1,
		'acc_balance': 89646862,
		'bank_name': 'Bank C',
		'bvn': 33189875234,
		'gender': 'Female',
		'marital_status': 'Divorced',
		'children': 'Yes',
		'resident_type': 'Parental Resident',
		'education_level': 'High School',
		'employment_status': 'Unemployed',
		'industry': 'Technology',
		'duration_of_employment': '3 years',
		'office_email': 'dunnmooney@petigems.com',
		'monthly_income': 9007,
		'loan_repayment': 772.5,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Chen Coffey',
				'phone_number': '+1 (869) 517-3089',
				'email': 'chencoffey@petigems.com',
				'relationship': 'Family',
			},
			{
				'fullName': 'Small Holcomb',
				'phone_number': '+1 (950) 532-3340',
				'email': 'smallholcomb@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Hawkins West',
				'phone_number': '+1 (868) 547-2885',
				'email': 'hawkinswest@petigems.com',
				'relationship': 'Friend',
			},
		],
	},
	{
		'id': '654e12a4571dc71aeab56999',
		'organization': 'Lendstar',
		'username': 'Hurst73',
		'email': 'hurstwest@petigems.com',
		'date_joined': 'Apr 16, 2021 09:39 AM',
		'status': 'Pending',
		'phone_number': '+1 (862) 441-3808',
		'acc_tier': 3,
		'acc_balance': 83923733,
		'bank_name': 'Bank A',
		'bvn': 59929174600,
		'gender': 'Male',
		'marital_status': 'Single',
		'children': 'No',
		'resident_type': 'Parental Resident',
		'education_level': "Master's Degree",
		'employment_status': 'Unemployed',
		'industry': 'Finance',
		'duration_of_employment': '3 years',
		'office_email': 'hurstwest@petigems.com',
		'monthly_income': 7617,
		'loan_repayment': 552.9,
		'socials': ['facebook'],
		'guarantor': [
			{
				'fullName': 'Riggs Kinney',
				'phone_number': '+1 (822) 456-3238',
				'email': 'riggskinney@petigems.com',
				'relationship': 'Friend',
			},
			{
				'fullName': 'Letitia Parsons',
				'phone_number': '+1 (880) 510-2857',
				'email': 'letitiaparsons@petigems.com',
				'relationship': 'Colleague',
			},
			{
				'fullName': 'Lessie Nixon',
				'phone_number': '+1 (804) 510-2430',
				'email': 'lessienixon@petigems.com',
				'relationship': 'Colleague',
			},
		],
	},
];
